### ISSUE TITLE
Powermeter data empty

### ISSUE THREAD

**Issue by taston** [RWTH-i5-IDSG/steve#115]
I have Chago Ensto charger. I have problems with power consumption usage.

In Charger I set meter values to:

![obraz](https://user-images.githubusercontent.com/22216384/53735291-bf727580-3e86-11e9-8f49-8d099d78bcc3.png)

But in database I see only "zero values":

![obraz](https://user-images.githubusercontent.com/22216384/53735363-e9c43300-3e86-11e9-988c-327f24fef1d2.png)

Any suggestions to set it to works propertly?
Or maybe I can debug data received from charger?

**Comment by goekay** [comment]
hi, we log the communication with the station (requests and responses) to the log file. i would advise to look for messages with the same timestamps whether the value is actually set in the message.

**Comment by goekay** [comment]
closing this issue due to its inactivity
