### ISSUE TITLE
Charge point authentication

### ISSUE THREAD

**Issue by sporubcan** [RWTH-i5-IDSG/steve#128]
Hi,
first of all, thank you very much for great work! I find Steve to be very useful and use it for testing of own OCPP1.6 client.

Question: There is something about charge point authentication described in paragraph 6.2.2 (OCPP 1.6 Specification - JSON.pdf). I think that this authentication feature isn't implemented in Steve. Would it be possible to implement this?
Thank you!
Best regards,
Samuel

**Comment by goekay** [comment]
> I think that this authentication feature isn't implemented in Steve.

correct. the security and authentication aspect of ocpp spec is reworked/enhanced with the new [OCPP 1.6 Security Whitepaper](https://www.openchargealliance.org/news/enhanced-security-for-ocpp-16/). the feature request to implement it has been expressed in #100. it is a TODO for future.
