### ISSUE TITLE
No protocol (OCPP version) 

### ISSUE THREAD

**Issue by solodoit** [RWTH-i5-IDSG/steve#135]
I add a chargeBox, but there no protocol 
![微信截图_20190507204224](https://user-images.githubusercontent.com/8099847/57300244-ff650b80-7108-11e9-8241-089b09e8f79a.png)
![微信截图_20190507204546](https://user-images.githubusercontent.com/8099847/57300295-1c014380-7109-11e9-99ca-b8941e7340b5.png)

**Comment by goekay** [comment]
the ocpp websocket spec requires the following in section "3.1.2. OCPP version" of the document "OCPP-J 1.6 Specification": 

> The exact OCPP version MUST be specified in the Sec-Websocket-Protocol field.

since your charging station does not specify one of the allowed values, steve does not accept the websocket connection attempt.

**Comment by rathourcode** [comment]
> Sec-Websocket-Protocol field.

hai goekay 

can you please tell how to specify ocppp version so that my websocket coonection works.
