### ISSUE TITLE
Cannot access wget https://github.com/RWTH-i5-IDSG/steve/archive

### ISSUE THREAD

**Issue by abdulgig** [RWTH-i5-IDSG/steve#144]
Under the configuration and installation document, 

wget https://github.com/RWTH-i5-IDSG/steve/archive/steve-X.X.X.tar.gz

However, this path is not accessible ==> https://github.com/RWTH-i5-IDSG/steve/archive

From where to download ?

My apologies, I am new to this.

Best Regards,

**Comment by goekay** [comment]
because it alone is not a path to be traversed. you should just change the X.X.X in the path above with the steve version you want to download and `wget` that path. or you know, visit the releases page and download the version you want: https://github.com/RWTH-i5-IDSG/steve/releases

**Comment by abdulgig** [comment]
Thanks
