### ISSUE TITLE
error after mvn package

### ISSUE THREAD

**Issue by Ivra23** [RWTH-i5-IDSG/steve#147]
Hello, 
I have this problem but i don't know what's this.
![image](https://user-images.githubusercontent.com/38098276/59842373-bbdffd00-9356-11e9-9e61-df144ff7c1f7.png)

Version of my Java and Maven 
![image](https://user-images.githubusercontent.com/38098276/59842429-d914cb80-9356-11e9-9f5b-297c8983ecf4.png)

Version of my WampServer
![image](https://user-images.githubusercontent.com/38098276/59842567-11b4a500-9357-11e9-9e5f-ed602e2f2a48.png)

Thank you

**Comment by goekay** [comment]
you should google the error message of the first screenshot. explanation: https://stackoverflow.com/a/45013815

**Comment by Ivra23** [comment]
Hello,
Thank you for your help,
now i have antahor problem with the version 3.3.0 

![image](https://user-images.githubusercontent.com/38098276/60358723-37851e00-99d7-11e9-8702-7062487eb335.png)

I put the correct time zone normally and give all guranted to the user steve
![image](https://user-images.githubusercontent.com/38098276/60358757-4cfa4800-99d7-11e9-8f5d-ca03278ced24.png)

Thank you

**Comment by goekay** [comment]
the database exception you see has nothing to do with the time zone. the exception message is clear: the user `steve` does not have the necessary permissions to access the database. please make sure that you executed the database preparation steps from readme.

**Comment by Ivra23** [comment]
Yes I followed step by step readme, but maybe the version of the mariadb it's not correct no ?
![image](https://user-images.githubusercontent.com/38098276/60359640-e4609a80-99d9-11e9-9311-ba0f4d1a6721.png)

**Comment by goekay** [comment]
i want to remind you the following: github issues are not a support channel.

maybe first try to connect as steve instead of root, to see if it works at all. and you are using mariadb version 10.1.23 even though in readme point out that 10.2.1 or later works.

**Comment by Ivra23** [comment]
oki thank you i will try.
