### ISSUE TITLE
Using "Trigger Message": Unable to see details of answe

### ISSUE THREAD

**Issue by MegasolEngineering** [RWTH-i5-IDSG/steve#152]
I'm using steve 3.2.
When using "Trigger Message" for example to get "MeterValues" from charging pile, it would be good to see the "Details" of the response, same as if using "Get Configuration".

I tried with tcpdump and got this:
**[4,"648","FormationViolation","The payload for action could not be deserialized",{"errorMsg":"Cannot deserialize value of type `ocpp.cs._2015._10.UnitOfMeasure` from String \"Celcius\": value not ..."}]**
Is this a problem from charger or steve? Should i report it as a separate issue (bug report)?
Btw I often send "Trigger Message" or "Get Configuration" / "Set Configuration" and get no response from charging pile. Is this normal behaviour or is it a buggy charger?

**Comment by goekay** [comment]
first of all, please use the issue templates. by using them we try to minimise redundant or duplicate questions.

> When using "Trigger Message" for example to get "MeterValues" from charging pile, it would be good to see the "Details" of the response, same as if using "Get Configuration".

hmm okay i can look into that.

> [4,"648","FormationViolation","The payload for action could not be deserialized",{"errorMsg":"Cannot deserialize value of type ocpp.cs._2015._10.UnitOfMeasure from String "Celcius": value not ..."}]
Is this a problem from charger or steve? Should i report it as a separate issue (bug report)?

this is already discussed in #145. the value "Celcius" should be "Celsius". it is spelling mistake by charging station developers.

> Btw I often send "Trigger Message" or "Get Configuration" / "Set Configuration" and get no response from charging pile. Is this normal behaviour or is it a buggy charger?

if the request message successfully exits steve, then yes it is a buggy charging station software. make sure that the station supports the triggered operations.
