### ISSUE TITLE
 log interpretation

### ISSUE THREAD

**Issue by Ivra23** [RWTH-i5-IDSG/steve#154]
Hello, 

In the log system, i have this info, why i can't acces to the server. 
I configured the main.properties like readme
![image](https://user-images.githubusercontent.com/38098276/60450017-39deb680-9c29-11e9-8620-674ba3c12b64.png)

Thank you,

**Comment by goekay** [comment]
once again, i want to remind you the following: github issues are not a support channel. you are abusing the issue system. please do not open any more issues.

moreover, you are misinterpreting the log. it does not state why you cannot access the server. taking your previous issues into account, i advise you to consult someone with more experience and know-how for help.
