### ISSUE TITLE
Dicussion: should we use github dependabot?

### ISSUE THREAD

**Issue by csamsel** [RWTH-i5-IDSG/steve#159]
https://github.com/marketplace/dependabot-preview

Can automatically make pull requests if it detects security issues in dependencies. Works with maven. Free of charge and it's provided by github themselves.  Sounds good to me.

Any objections?

**Comment by goekay** [comment]
sure. why not. if we are not satisfied with it, we can always disable it.

however, i tried using it a while ago after seeing a security issue notification. it failed, because it could not handle version properties/variables which we use. hopefully they improved it.

**Comment by csamsel** [comment]
Agreed. I cannot set it up because i'm not an owner of the organization anymore.

**Comment by muued** [comment]
should now be set up

**Comment by goekay** [comment]
thanks
