### ISSUE TITLE
Upgrade to 3.3.1

### ISSUE THREAD

**Issue by kernelkraut** [RWTH-i5-IDSG/steve#161]
This may not be a bug specifically but we are struggling to upgrade from 3.3.0 to 3.3.1 - We have downloaded the new release and run mvn package but mvn keeps building the old version. We are very new to mvn so please forgive the stupid question but how to we upgrade?

#### Specifications

SteVe Version     :  3.3.0
Operating system  : CentOS
JDK               :  11
Database          : MariaDB

**Comment by goekay** [comment]
ups. my bad. forgot to bump the version in maven before making the release =/

this does not change the functionality, though. if you download and build the latest commit, it has the bugfix.

**Comment by kernelkraut** [comment]
Awesome thanks!

**Comment by goekay** [comment]
i fixed the release. now it points to the correct commit with the version change. sorry for the confusion.

**Comment by kernelkraut** [comment]
Thanks for the quick help today!
