### ISSUE TITLE
Hot deployment

### ISSUE THREAD

**Issue by qwqeq** [RWTH-i5-IDSG/steve#194]
I wanna to know how to set up Hot deployment while I'm developing.

**Comment by qwqeq** [comment]
Why doesn't the page show my changes when I modify the JSP file

**Comment by goekay** [comment]
the jsp files have to be compiled to normal java classes for them to be usable. at the moment this is done when building the project. so you have to rebuild steve and restart it.

**Comment by qwqeq** [comment]
@goekay But if I do as you said,my development efficiency will be extremely low. If I change one word in a jsp file and then I have to rebuild steve and restart it.

**Comment by goekay** [comment]
i agree, it's not optimal. hot reloading/deployment is currently not possible. but i will look into it to improve things for the dev environment.

**Comment by qwqeq** [comment]
@goekay I would like to know how you developed Steve. When you modified the JSP file, did you do what you said? Recompile and restart Steve

**Comment by goekay** [comment]
yeah, sure. it works but you have to think ahead and have a mental model of the consequences of what you are doing. that eliminates the guesswork and frequent recompiles/restarts.

**Comment by goekay** [comment]
by the way, you copied [steve](https://github.com/qwqeq/steve) without any reference to the original repo. moreover, you deleted the contents of the readme & license files and stripped away the copyright notice at the header of each file. not cool. you have to adhere to our license and copyrights.

another recent case was [here](https://github.com/RWTH-i5-IDSG/steve/issues/145#issuecomment-502453196). make sure you read my comments about what you can and cannot do with steve.

![steve_qwqeq](https://user-images.githubusercontent.com/3861031/64528976-10699780-d30a-11e9-97f6-a743ddb14396.jpg)

![steve_qwqeq_git_log](https://user-images.githubusercontent.com/3861031/64528999-1bbcc300-d30a-11e9-8c8a-eae76b8c4139.png)

**Comment by ijazm123** [comment]
@goekay Can I package this to war file and deploy in tomcat?

**Comment by csamsel** [comment]
No
