### ISSUE TITLE
Hubject/OICP integration

### ISSUE THREAD

**Issue by goekay** [RWTH-i5-IDSG/steve#2]

**Comment by ahzf** [comment]
Hi, there...

as I'm currently busy with developing a JAVA version of my OICP C# project I would be interested where in your code base I could find s.th. like hooks for:

 - An incoming RFID auth (start) request, in order to dispatch it to Hubject whenever the Id/AuthToken was not found within Steve
- The same for RFID auth stop
- An incoming remote start request
- An incoming remote stop request
- After the charging process is finished: Where to get the trigger and data for sending a charging detail record.

Thanks a lot...
  Achim

**Comment by goekay** [comment]
Hello,

-  *An incoming RFID auth (start) request, in order to dispatch it to Hubject whenever the Id/AuthToken was not found within Steve*
[Here](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/service/UserServiceImpl.java#L45) and [here](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/service/UserServiceImpl.java#L78) (OCPP version specific)

- *The same for RFID auth stop*
Can you please elaborate what you mean with that? 

- *An incoming remote start/stop request*
Currently, these can only be triggered via the Web page. We do not have an API yet.

-  *After the charging process is finished: Where to get the trigger and data for sending a charging detail record*
The implementation here is once again version specific: [Here](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/service/CentralSystemService12_Service.java#L132) and [here](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/service/CentralSystemService15_Service.java#L147). These are messages arriving from the charging station, though, and do not provide a detailed charging record. For this, depending on the wanted data, additional database calls might be necessary to retrieve other related info.

**Comment by goekay** [comment]
Can you please inform us about the scope your project? Is it just a translation of the OICP C# project, or a complete OICP integration with Steve? The reason I am asking is... I see you work for GraphDefined and forked Steve. We also started working on the Hubject/OICP integration.

**Comment by ahzf** [comment]
Hi... it's not a real project. I just was asked by Hubject to help a little bit, as their documentation is still a bit "sparse", but improving ;) I had a phone call with Dr. Karl-Heinz Krempels a couple of weeks ago and he told me, that it might be a good thing if at least a bit would be ready till this year's eCarTec.

**Comment by ahzf** [comment]
Hi again,
at https://github.com/GraphDefined/jOICP you will find a rough Java 1.8+ implementation of OICP v2.0. Perhaps this will help you within your own code base :)

Best from Jena
  Achim

**Comment by goekay** [comment]
development/implementation is finished. waiting for approval from hubject to put it online. therefore, we can close the issue.

**Comment by goRaspy** [comment]
Great news !
Is the Hubject implementation could works simultaneously with PlugSurfing ?

**Comment by goekay** [comment]
no, unfortunately not.

**Comment by goRaspy** [comment]
Tks for the precision.

**Comment by ahzf** [comment]
@goekay Will it the Hubject connector be fully Open Source? ;)

**Comment by goekay** [comment]
depends totally on them. the ball is in their court. the integration principle was the same as with plugsurfing (https://github.com/RWTH-i5-IDSG/steve-plugsurfing). if they give the green light, you will see  another steve repo with a similar approach.

**Comment by ahzf** [comment]
Any news on that?

**Comment by goekay** [comment]
nope. you should contact and ask hubject, if you want to see any progress.
