### ISSUE TITLE
How Can the Application Connect to ChargeBox with Encrypted ID?

### ISSUE THREAD

**Issue by MikeK19** [RWTH-i5-IDSG/steve#211]
Hi,

I would like to use the application to test OCPP compliance for a vendor chargers. How can I set the application to connect to the chargers which I don't know their ChargeBox ID (encrypted). The chargers are in different network domain. 

Thank you

**Comment by goekay** [comment]
> How can I set the application to connect to the chargers which I don't know their ChargeBox ID (encrypted).

i think you have a misunderstanding how steve works with stations. you configure the stations to connect to steve, and not the other way around. if the stations are not registered in database, you should see exceptions in the log file and can find out the chargebox id there. as an alternative, you can change [this setting](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/resources/config/prod/main.properties#L51) to accept all communication attemps from unknown stations.

**Comment by MikeK19** [comment]
So the charger should be configured to communicate to SteVe.  Did you have a test case that Steve had been tested with ABB chargers? I didn't find ABB is the compatible devices list.

**Comment by goekay** [comment]
no. then please test and update the list ;)
