### ISSUE TITLE
ReserveNow request should accept connectorId >= 0

### ISSUE THREAD

**Issue by tintigx** [RWTH-i5-IDSG/steve#214]
Hi,

According to the OCPP1.6 specification, the ReserveNow.req should accept connectorId >= 0.
Is this possible to add this possibility to Steve ? On the master branch, the minimum value is 1.

**Comment by goekay** [comment]
this is one aspect where we diverge from the spec on purpose. it was mainly done for roaming extensions, which reserve/book connectors and therefore we needed to restrict the flexibility. more info: https://github.com/RWTH-i5-IDSG/steve/issues/21
