### ISSUE TITLE
Stoping a active transaction from data management menu

### ISSUE THREAD

**Issue by geldek** [RWTH-i5-IDSG/steve#235]
1. start a transaction (either by remote start transaction or locally from charging station)
2. navigate to "Data Management" - "Transactions" menu
3. as long as the transaction is active there is a "Stop" button visible in the last column
4. click "Stop"
5. "transaction_stop" table in the database is updated, however, no message is sent to the charging point and the transaction remains active
6. not possible to stop the transaction from Steve by using "Remote Stop Transaction" (other than deleting the row from transaction_stop table)

**Comment by goekay** [comment]
the use case of stopping transactions from data management menu is a bit different. it is there for killing "zombie" transactions that never were stopped. therefore, it applies to corner cases and should not be used in normal situations.

related issue: #94
