### ISSUE TITLE
I cant install the application 

### ISSUE THREAD

**Issue by eviontech** [RWTH-i5-IDSG/steve#246]
#### Checklist

- [ 
[steve.log](https://github.com/RWTH-i5-IDSG/steve/files/3935474/steve.log)
] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : latest
Operating system  : window server
JDK               : latest
Database          : mysql 8
```

#### Expected Behavior

succesful install

#### Actual Behavior

failed

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context

...

**Comment by csamsel** [comment]
If you look at the log file you can see the error. Timezones are not configured correctly. Everything (System, Java, MySQL) has to be in UTC.
