### ISSUE TITLE
statusNotification status update not working

### ISSUE THREAD

**Issue by eviontech** [RWTH-i5-IDSG/steve#250]
#### Checklist

- [ ] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : latest
Operating system  : ...
JDK               : ...
Database          : ...
```

#### Expected Behavior

status should change to available

#### Actual Behavior
status should change but status remains preparing as initially set..

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context

...
![image](https://user-images.githubusercontent.com/39265755/70773098-80216f80-1d9c-11ea-8330-c99b8c5b34ee.png)

![image](https://user-images.githubusercontent.com/39265755/70773114-8b749b00-1d9c-11ea-8d52-e31b3a2cb81d.png)

**Comment by goekay** [comment]
the timestamp of the status message with "preparing" (5th line in logs) is later than the status with "available". therefore, steve selects the most recent status.

**Comment by eviontech** [comment]
![image](https://user-images.githubusercontent.com/39265755/70773779-6123dd00-1d9e-11ea-980c-da6a290e829e.png)

**Comment by goekay** [comment]
the time when we receive the messages does not matter. the timestamp of the message counts. there can be thousand messages before `11:08:51`. steve will still pick this one since it is the most recent. probably, the station had a wrong internal clock and the message was queued before applying the current time in response to boot notification.

**Comment by eviontech** [comment]
ok understood
thanx

**Comment by goekay** [comment]
to further clarify: the time of the log line does not matter. the value of the timestamp property in the message counts.

**Comment by eviontech** [comment]
a quick question other than the topic raised

can we change web ui timezone to IST in anyway.... only the display

**Comment by eviontech** [comment]
and also can we remove functionalities from our setup ... like we are not implementing parent id concept

**Comment by goekay** [comment]
you are targeting multiple topics in one issue. github issues are not a support channel. please be mindful of that. only open issues if you believe that it is a problem with steve. and please use issue templates to rule out duplicates.

> can we change web ui timezone to IST in anyway.... only the display

no, there is an open issue for this feature request: https://github.com/RWTH-i5-IDSG/steve/issues/96

> and also can we remove functionalities from our setup ... like we are not implementing parent id concept

then don't use it. steve supports multiple features to cover various different use cases. if you do not need parent id tags, do not set them in id tags.
