### ISSUE TITLE
stopTransaction after tag expiry

### ISSUE THREAD

**Issue by eviontech** [RWTH-i5-IDSG/steve#252]
If a ocpp tag starts a transaction and then while transaction is active it expires

currently there is no way to stop the transaction

**Comment by goekay** [comment]
> currently there is no way to stop the transaction

can you elaborate on that? the transaction is stopped by the station.

**Comment by eviontech** [comment]
a transaction was started by station using a ocpp tag

while transaction was not completed the tag expired

now station cannot stop the transaction

**Comment by goekay** [comment]
> now station cannot stop the transaction

this is what i wrote, as well. the station decides. not steve. the backend cannot do anything about this. maybe you should raise this problem by the station manufacturer.

**Comment by eviontech** [comment]
let me check if station can stop the trannsaction

**Comment by goekay** [comment]
i want to remind you once again to follow the guidelines of the issue template. by not following the guidelines you do not give the full context in detail for me to help you. you are opening issues that are about problems unrelated to steve, as well.
