### ISSUE TITLE
hi how are you.

### ISSUE THREAD

**Issue by shill93888** [RWTH-i5-IDSG/steve#268]
Missing jooq.stteve package when configuring steve project

![image](https://user-images.githubusercontent.com/59836842/72331025-71f3a580-36f2-11ea-8e8e-a4be87db9047.png)

I don't know how to solve it, can it help me?
thank you！

**Comment by shill93888** [comment]
jooq.steve.db 
Without this bag

**Comment by csamsel** [comment]
you have to build it to generate the flyway classes
