### ISSUE TITLE
Add "Unknown Charge Point": ChargePoint ID is altered

### ISSUE THREAD

**Issue by ue-lee** [RWTH-i5-IDSG/steve#270]
#### Specifications
```
SteVe Version     :  3.4.1
Operating system  : Debian 10
JDK               : 11.0.5
Database          : MySQL 14.14, Distribution 5.7.29
```

#### Expected Behavior
Webinterface: Data Management -> Charge Points
After pushing "Add" in "Unknown Charge Points" for e.g. ChargeBox ID "15999999_19999.0B", Charge Point should vanish from this category ("Unknown Charge Points") and should be listed under "Charge Point Overview".

...

#### Actual Behavior
After pushing "Add" in "Unknown Charge Points" for e.g. ChargeBox ID "15999999_19999**.0B**", Charge Point is still listed in this category ("Unknown Charge Points") but also listed unter "Charge Point Overview", but with ChargeBoxID "15999999_19999". The part after "." is missed out.
...

#### Steps to Reproduce the Problem

  1. Set up ChargePoint with ID, containing "." or maybe any other special characters 
  2. Try adding it unter "Unknown Charge Points"

![unknown_cp](https://user-images.githubusercontent.com/7364359/72351822-6055d200-36e1-11ea-9596-3232b02b36ab.PNG)

![added_cp](https://user-images.githubusercontent.com/7364359/72351826-62b82c00-36e1-11ea-8292-5d85bd945534.PNG)

**Comment by goekay** [comment]
hi, thanks for the detailed issue report. it is a valid bug. i will commit the fix to provide the expected behaviour in a few minutes.

**Comment by ue-lee** [comment]
Thanks for the fast patch!
