### ISSUE TITLE
RFID-Card function

### ISSUE THREAD

**Issue by ben3123** [RWTH-i5-IDSG/steve#274]
#### Checklist

- [ ] I checked other issues already and found no answer
- [ ] I checked the documentation and found no answer
- [ ] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve
Can I use an RFID card reader in combination with the server?
How / where can I implement RFID cards?

Thank you for help.

**Comment by csamsel** [comment]
SteVe is a backend system. The RFID cards are read by the charging station. You can add a rfid tag in the SteVe GUI and then authorization requests using this tag are validated by steve.
