### ISSUE TITLE
Am using M2M SIM for connecting to SteVe from the charge point

### ISSUE THREAD

**Issue by GRangaRao** [RWTH-i5-IDSG/steve#276]
With M2M SIM charge point never connects to SteVe dashboard 

1. M2M SIM relies on ppp0 in Linux
2. ethernet defaults to eth0 (with ethernet works fine)

Anyone tried with wireless M2M SIM?

**Comment by goRaspy** [comment]
Using M2m sim cards without static IP or vpn can only works with json
charging stations.

Are you using soap charging stations ?



Le ven. 24 janv. 2020 à 12:54, GRangaRao <notifications@github.com> a
écrit :

**Comment by goekay** [comment]
sorry but this sounds like a charging station problem. we cannot provide any help for stations. i am closing this issue, since it is outside the scope of steve. feel free to continue the discussion.
