### ISSUE TITLE
Any guidance to add a charge point is appreciated

### ISSUE THREAD

**Issue by ijazm123** [RWTH-i5-IDSG/steve#279]
Need to know how to add a charge point

**Comment by csamsel** [comment]
Feel free to read the documentation: https://github.com/RWTH-i5-IDSG/steve
It's described in detail there.

**Comment by ijazm123** [comment]
while adding the charger point I am getting an error 'Registration status is required'

**Comment by ijazm123** [comment]
> Feel free to read the documentation: https://github.com/RWTH-i5-IDSG/steve
> It's described in detail there.

while adding the charger point I am getting an error 'Registration status is required'

**Comment by goekay** [comment]
> while adding the charger point I am getting an error 'Registration status is required'

this was a bug that was reported and i fixed recently (#248). but i did not make a release after the fix, yet. so, if you are using the latest release version, this error will happen.

i will make a release later based on the latest commit. until then, you can 'git pull' the repo use it.

**Comment by goekay** [comment]
i made a new release which includes the fix: https://github.com/RWTH-i5-IDSG/steve/releases/tag/steve-3.4.2

sorry for the inconvenience.

**Comment by ijazm123** [comment]
> i made a new release which includes the fix: https://github.com/RWTH-i5-IDSG/steve/releases/tag/steve-3.4.2
> 
> sorry for the inconvenience.

Thank you so much. Now the issue is resolved.
