### ISSUE TITLE
Question: range of integer types (transactionId, ...)

### ISSUE THREAD

**Issue by lategoodbye** [RWTH-i5-IDSG/steve#280]
Still after reading the OCPP 1.6 specification it's not clear me, what range the several integer types like transactionId, chargeProfileId, reservationId, listVersion have.

Is there some kind of minimum range, which all CP implementations should support?
Should i assume these all can be signed?

**Comment by csamsel** [comment]
I agree it's not well defined. Personally i would have assumed 32bit unsigned integer.

**Comment by lategoodbye** [comment]
Looking at the OCPP 2.0 spec shows a better definition. The primitive type "integer" is defined as signed 32 bit integer, which is easier in Java. But the seqNo for the transaction should be 32 bit unsigned.

**Comment by lategoodbye** [comment]
Except of the specification, it would be nice to know the ranges of the SteVe implementation.

**Comment by goekay** [comment]
transactionId, chargeProfileId, reservationId are backed by the database primary key type. therefore, they are auto incrementing, unsigned INT types in MySQL (https://dev.mysql.com/doc/refman/5.7/en/integer-types.html)

listVersion is not persisted in database. the user is responsible to choose it as she sees fit. its data type is an int  in Java (32 bit, signed)

**Comment by goekay** [comment]
i consider the question answered and this issue resolved. therefore, closing it.
