### ISSUE TITLE
"Result not found" Exception on response (GetCompositeSchedule) details

### ISSUE THREAD

**Issue by elec-gio** [RWTH-i5-IDSG/steve#300]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.2
Operating system  : Debian 10
JDK               : 11.0.6
Database          : MySQL 14.14, Distribution 5.7.29
```

#### Expected Behavior

show the details of the response similar to the log? idk, only have around 10 tasks history, mainly for smartcharging purposes.
edit: also happens with GetConfiguration

#### Actual Behavior

With click on the response details the following notification is on-screen:
![grafik](https://user-images.githubusercontent.com/61496141/75330052-f8b6a900-5880-11ea-8714-effef5887352.png)

#### Steps to Reproduce the Problem

  1. operation "GetCompositeSchedule" in OCPP 1.6, wait for response (with/or without current active SmartChargingProfile on client)

#### Additional context
steve- log excerpt:
```
[INFO ] 2020-02-26 06:40:37,838 org.apache.cxf.services.CentralSystemService.RESP_OUT - 
    ExchangeId: 2ca0e62a-40b2-4627-a00c-e1b0075557a0
    Payload: <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><Action xmlns="http://www.w3.org/2005/08/addressing">/HeartbeatResponse</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:7b212c7d-7fd1-4fdd-8007-6704806a31f0</MessageID><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">DDEF244C-B14D-4B53-8D72-CC4EB0A3A43E</RelatesTo></soap:Header><soap:Body><heartbeatResponse xmlns="urn://Ocpp/Cs/2015/10/"><currentTime>2020-02-26T06:40:37.816+01:00</currentTime></heartbeatResponse></soap:Body></soap:Envelope>
[ERROR] 2020-02-26 08:53:16,480 de.rwth.idsg.steve.web.GlobalControllerAdvice - Request: http://10.1.0.250:8080/steve/manager/operations/tasks/7/details/18000285_10632.0A raised following exception.
de.rwth.idsg.steve.SteveException: Result not found
	at de.rwth.idsg.steve.web.controller.TaskController.extractResult(TaskController.java:113) ~[steve.jar:?]
	at de.rwth.idsg.steve.web.controller.TaskController.processForGetCompositeScheduleTask(TaskController.java:93) ~[steve.jar:?]
	at de.rwth.idsg.steve.web.controller.TaskController.getDetailsForChargeBox(TaskController.java:84) ~[steve.jar:?]
```

**Comment by goekay** [comment]
thanks for the bug report. it is a valid bug and is caused by the same problem as in #270: if the charge point contains a dot in its id, our web framework drops the part after the dot while processing the url. since there is no task result for the first part only, you get this exception. in the mentioned issue, i fixed it only locally, which was a mistake on my part.

i will try to find a general solution for this case, since we have multiple paths that include a chargepoint in url.
