### ISSUE TITLE
Is there a guide to get started using steve server ?

### ISSUE THREAD

**Issue by mkj-git** [RWTH-i5-IDSG/steve#307]
Is there any simple and clear cut example of how to connect to steve server using a program, simulator ? 
I am unable to find a simple example that will explain how can we get started with using steve server. Whatever examples are available, it too complicated or not well documented to understand.

**Comment by goekay** [comment]
all we have is the main readme page and other wiki pages. if you encounter problems, such as the ones you listed, please make a pull request to update/fix them.
