### ISSUE TITLE
HTTPS implement

### ISSUE THREAD

**Issue by aziz-khalapoum** [RWTH-i5-IDSG/steve#31]
Hello,

I would like to know what are the steps and the configuration to make to set up the https. I saw that the configuration file foresees it : 
# Jetty HTTPS configuration
#
https.enabled = false
https.port = 8443
keystore.path =
keystore.password =

thank you

**Comment by goekay** [comment]
hello, well first you have to enable https and change the port (if you wish). the main part, though, is configuring the container for certificates for java applications with the java keytool. there are many tutorials that you can google and find, but here is one to get you started: https://www.digitalocean.com/community/tutorials/java-keytool-essentials-working-with-java-keystores

**Comment by aziz-khalapoum** [comment]
hello, 
I was able to make it work.Thank you for your help.

**Comment by josecharry** [comment]
Thanks for your answers. I implemented https creating a repository of keys with the following cmd: _keytool -genkey -alias **test** -keyalg RSA -keystore **test.jks** -keysize 2048_ , then you have to put the path and the pass in main.properties.

**Comment by rdc-Green** [comment]
How do you find the path @josecharry to enter into main.properties after entering the cmd?

**Comment by rdc-Green** [comment]
I found it in /home/user/test.jks
