### ISSUE TITLE
How can I service backend API with Steve

### ISSUE THREAD

**Issue by sunearthdolpin** [RWTH-i5-IDSG/steve#315]
I am a mobile app developer. So I am going to develop backend API for my mobile app.
Please help me.

**Comment by csamsel** [comment]
Change/Extend the Java server pages to scale well to mobile devices.
There is really no point in building a native app.

**Comment by goekay** [comment]
hello, your question is too vague for us to answer. besides, we are leaving the scope of steve with such support questions. please use github issues only if you have problems with steve itself.
