### ISSUE TITLE
VendorErrorCode not stored in databas

### ISSUE THREAD

**Issue by goRaspy** [RWTH-i5-IDSG/steve#32]
I thinks there is a small issue with recording of status notifications in database.

File 
steve/src/main/java/de/rwth/idsg/steve/repository/impl/OcppServerRepositoryImpl.java

WAS
 .set(CONNECTOR_STATUS.VENDOR_ERROR_CODE, **p.getErrorCode())**
SHOULD BE
 .set(CONNECTOR_STATUS.VENDOR_ERROR_CODE, **p.getVendorErrorCode())**

Cheers

**Comment by goekay** [comment]
you are correct. i will push the fix in a few minutes. thanks for the report!

**Comment by goRaspy** [comment]
my pleasure :)
