### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by GRangaRao** [RWTH-i5-IDSG/steve#326]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...3.4.1
Operating system  : ...18.04 Ubuntu
JDK               : ...open jdk 11
Database          : ...MySQL 5.7 community server
```

#### Expected Behavior

Java -jar target/steve.jar should pass
...

#### Actual Behavior

Java -jar target/steve.jar  fails

log in /root/log/steve.log shows
[steve.log](https://github.com/RWTH-i5-IDSG/steve/files/4522609/steve.log)

[ERROR] 2020-04-23 13:47:41,267 de.rwth.idsg.steve.SteveProdStarter - Exception happened
de.rwth.idsg.steve.SteveException: MySQL and Java are not using the same time zone. Java offset in seconds (0) != MySQL offset in seconds (3600)

...

#### Steps to Reproduce the Problem

  1. ...
  2. ...
  3. ...

#### Additional context

...

**Comment by goekay** [comment]
we had this already multiple times: https://github.com/RWTH-i5-IDSG/steve/issues/139 https://github.com/RWTH-i5-IDSG/steve/issues/318
