### ISSUE TITLE
Mail boot notifcation on not registrered JSON Station

### ISSUE THREAD

**Issue by goRaspy** [RWTH-i5-IDSG/steve#33]
When Steve received a boot notification for a not registrered SOAP station. Steve send an email "Charging station 'XXXX' is NOT registered.".

This is not working for JSON station and very usefull :(

**Comment by goekay** [comment]
this is easy to implement and i'm on it. one question: do the registered json charging stations send a boot notification message after successful websocket connection?

**Comment by goRaspy** [comment]
Awesome :)

Yes, notificatiosn works fine on registrered JSON stations

**Comment by goRaspy** [comment]
Works fine, you are the best !

Many thanks
