### ISSUE TITLE
Add SupportedFileTransferProtocols to Get Configuration (OCPP 1.6)

### ISSUE THREAD

**Issue by lategoodbye** [RWTH-i5-IDSG/steve#337]
#### Checklist

- [X] I checked other issues already and found no answer
- [X] I checked the documentation and found no answer
- [X] I am running the version 3.4.2 and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

OCPP 1.6 errata v4.0 defines a "new" configuration key called SupportedFileTransferProtocols. SteVe misses this parameter in its select list under /steve/manager/operations/v1.6/GetConfiguration

#### Describe the solution you'd like

It would be nice to add this configuration key into the parameter select list for Get Configuration.

**Comment by goekay** [comment]
thanks for the heads-up @lategoodbye !
