### ISSUE TITLE
Order configuration keys alphabetically

### ISSUE THREAD

**Issue by lategoodbye** [RWTH-i5-IDSG/steve#344]
#### Checklist

- [X] I checked other issues already and found no answer
- [X] I checked the documentation and found no answer
- [ ] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

As a user the order of the configuration keys in the select list under "Get Configuration" and "Change Configuration" looks random and not user-friendly.

#### Describe the solution you'd like

It would be great to order alphabetically the entries in the select lists, but also the results of "Get Configuration".

**Comment by goekay** [comment]
currently, the order of keys follows the declaration order in `ConfigurationKeyEnum`. i agree that it would be better to order them alphabetically. the fix is simple. working on it.
