### ISSUE TITLE
adding a OCPP Tag List does not work

### ISSUE THREAD

**Issue by bkisters** [RWTH-i5-IDSG/steve#350]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.3
Operating system  : ubuntu 20.04
JDK               : openjdk 11.0.7
Database          :  mariadb  10.3
```

#### Expected Behavior
Import full list of transponder ids
#### Actual Behavior
Error:

org.jooq.exception.DataAccessException: SQL [insert into `stevedb`.`ocpp_tag` (`id_tag`) values (?)]; Duplicate entry '995C65BB' for key 'idTag_UNIQUE'
Reason:

java.sql.BatchUpdateException: Duplicate entry '995C65BB' for key 'idTag_UNIQUE'

#### Steps to Reproduce the Problem

  1. go to ocpp tag list 
  2. insert list of  tags seperated  by newline
  3. click add all

#### Additional context

...

**Comment by goekay** [comment]
as the exception states, you already have an idTag '995C65BB' in the table and trying to insert another one.

**Comment by bkisters** [comment]
yes, it seems as if there is already that idTag within steve, but I can't find it in the list of tags (datamanagement > ocpp tags )

**Comment by goekay** [comment]
maybe you have it twice in the list that you are trying to insert?

**Comment by bkisters** [comment]
no. this is the list i actually trying to insert

A1F4FD89
016B65BB
995C65BB
is there a sql table I can search it for?

**Comment by goekay** [comment]
of course: `stevedb.ocpp_tag`

**Comment by bkisters** [comment]
ok, it is in that table
and now?

**Comment by goekay** [comment]
well.. do not insert it twice.
