### ISSUE TITLE
SteVe does not read old transactions

### ISSUE THREAD

**Issue by bkisters** [RWTH-i5-IDSG/steve#353]
I was able to successfully read out all transactions of a Mennekes Gatway via a test installation of SteVe.
Now I have completely rebuilt SteVe again (also new database). Unfortunately, SteVe now only reads the new transactions.
SteVe does not read old transactions anymore. Why is that?

**Comment by goekay** [comment]
> Now I have completely rebuilt SteVe again (also new database)

since you recreated the database, the old database with all of its information is gone, deleted. therefore, previous transactions are deleted. that's why you cannot see/find them.

**Comment by bkisters** [comment]
I thought transactions would be retrieved again from the ChargePoint (Mennekes Gateway) during a new installation from SteVe

**Comment by goekay** [comment]
no, it does not happen.

**Comment by goekay** [comment]
in the recent days you opened many issues that were unrelated to an actual problem in steve. please keep in mind, that we do not provide any customer support. github issues are not a support channel.
