### ISSUE TITLE
SMTP email settings

### ISSUE THREAD

**Issue by GRangaRao** [RWTH-i5-IDSG/steve#354]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...3.4.3
Operating system  : ...Ubuntu 18.04
JDK               : ...OpenJDK 11
Database          : ...MySQL
```

#### Expected Behavior
Steve should send an email through smtp server
...

#### Actual Behavior
Failed to connect, Timeout exception
SMTP configuration settings are correct, tested with
https://www.gmass.co/smtp-test
...

#### Steps to Reproduce the Problem

  1. ...Configured SMTP settings for 587 port 
  2. ...Send Test Mail
  3. ...Failed to connect Timeout exception

#### Additional context
Error:
de.rwth.idsg.steve.SteveException: Failed to send mail

Reason:
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 587; timeout -1; nested exception is: java.net.ConnectException: Connection timed out (Connection timed out)
...

**Comment by GRangaRao** [comment]
@csamsel 
@goekay 

Could you please answer this query on smtp email?

**Comment by csamsel** [comment]
The error message is clear, the mail server is not reachable.

**Comment by GRangaRao** [comment]
Hi csamsel, Mail could be sent with another smtp server by using the same credentials, steve smtp is not working for any reason? is there any configuration option that is missed to add?

**Comment by goekay** [comment]
hi @GRangaRao, the fact that another server (https://www.gmass.co/smtp-test) can reach your smtp server does not mean that the server, where steve is deployed, can reach your smtp server. i would suggest to check the network settings.

**Comment by csamsel** [comment]
As @goekay said.
Could be an outgoing packet filter preventing that the server can send an email.

**Comment by GRangaRao** [comment]
@goekay , @csamsel

server where steve is deployed, i could send the e-mails through smtp with gmass.co/smt-test.

ufw status in ubuntu has port 587 open 

8080/tcp                    ALLOW       Anywhere
25/tcp (v6)                 ALLOW       Anywhere (v6)
587 (v6)                     ALLOW       Anywhere (v6)
587/tcp (v6)               ALLOW       Anywhere (v6)

Still some settings needs correction, as steve could not send emails through SMTP
seeing connection timeout

Thanks for your time!

**Comment by csamsel** [comment]
I have nothing to add. If you would try to send an mail from the server where steve is running you would see it isnt working.

btw. the ufw output has the ports only listed as open in IPv6.
