### ISSUE TITLE
Input field for custom GetConfiguration parameter(s)

### ISSUE THREAD

**Issue by lategoodbye** [RWTH-i5-IDSG/steve#363]
#### Checklist

- [X] I checked other issues already and found no answer
- [X] I checked the documentation and found no answer
- [X] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

As the Open Charge Alliance doesn't recommend to provide custom config parameter for a empty GetConfiguration request, it would be nice to have the ability to get the value of custom config parameter more reliable.

#### Describe the solution you'd like

I suggest to add a text input field for one or more custom GetConfiguration parameters similiar to Change Configuration (keys can be separated by commas). Plus a selectbox for the keytype Predefined / custom.

As a benefit this gives a tester of a OCPP client implementation the chance to check some error cases (unknown config parameter).

**Comment by goekay** [comment]
hey @lategoodbye, i am looking into this at last. i see your changes in your fork using your suggestion... however, i want to take a different and simpler approach:

i don't want to have dropdown menu to select predefined or custom. it should not be an either-or decision. i plan to add a text field where you can insert a comma separated list of custom keys. these can be sent to the station in addition to standard/predefined keys.
