### ISSUE TITLE
Unable to use SteVe in a cross-compiled environment due to  'migrate' goal under 'generate-sources'

### ISSUE THREAD

**Issue by aduskett** [RWTH-i5-IDSG/steve#366]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version, and the feature I am requesting is not implemented there

#### Describe the problem you are trying to solve
I want to use SteVe in a cross-compiled environment (Mainly Buildroot.) However, due to the migrate goal under the 'generate-sources' execution, this is currently not possible.

In issue #320 a reason behind running the migration during the build instead of on first run is:

```we encourage to build steve there, where it will be run. every other approach is very error-prone (for example java version differences).```

The problem with this is in a cross-compiled environment:
 - The host may not have the same Java version as the target.
 - The host might not have a MariaDB or MySQL instance running.
 - The target won't have Maven.
 - The target may not have a full JDK instance.

Even if the host does have a server running, it is unlikely that the servers will have the same credentials as the target. Also, running MariaDB from a target during the build process is not possible because it may (and usually is) compiled for a different architecture than the host PC.

#### Describe the solution you'd like
Make running the migration on startup vs. on packaging an option.

**Comment by csamsel** [comment]
The database connection is not only needed for database migration, but also for the generate-sources target, so moving the migration to runtime would not be enough.

Changing both would require to ditch jooq which would require a (more or less) rewrite of the database abstraction.
