### ISSUE TITLE
Liteon 1.6J OCPP compliant evse not connecting....

### ISSUE THREAD

**Issue by retrocoder-78** [RWTH-i5-IDSG/steve#376]
Hello!

Wanting to play and get familiar with the latest SteVe software, I am attempting to connect an evse I have in my possession. I am using a raspberry pi as the server. I have followed the SteVe setup and everything works when I test within my home network. 

https://github.com/victormunoz/OCPP-1.6-Chargebox-Simulator

That's to say that the html testing does what it should do within the SteVe software. Which is really great. 

But, when I point the evse (defaulted to factory settings) at the same ws address as the test html but with the correct chargebox id registered in the test html and SteVe, nothing. I have changed options and setup SteVe a couple of times and the same result. I have changed OCPP options in the firmware of the charger too. There must be something simple I am missing....I have played with a couple of different evse's in regards to OCPP and they range from well laid out in their firmware to a total mess. This liteon unit seems pretty well laid out in regards to OCPP. So, seemingly should work with SteVe with little effort. But, not yet....

Any thoughts, comments, or a point in the correct direction would be much appreciated.

I have included some screenshots and the manual of the evse as support documentation.

Thanks!

-----------------
[Users-Manual-rev-pdf-4325734.pdf](https://github.com/RWTH-i5-IDSG/steve/files/4973830/Users-Manual-rev-pdf-4325734.pdf)
-----------------
![1_factory_settings](https://user-images.githubusercontent.com/68619253/88426677-74703f80-cda6-11ea-8a5d-14384e5849a2.jpg)
![2_station_settings](https://user-images.githubusercontent.com/68619253/88426694-7a662080-cda6-11ea-9785-58c1a7366748.jpg)
![3_ocpp_settings](https://user-images.githubusercontent.com/68619253/88426707-7e923e00-cda6-11ea-9137-75ab29dd9c12.jpg)

**Comment by goekay** [comment]
hey, i don't think you are supposed to add the charge point id to the central system url as it is the case in your screenshot. yes, it is required to be there, but i think charging station software might add it automatically.

i imagine that the url in your case contains the id twice, e.g. `ws://.../1A30.../1A30`

**Comment by retrocoder-78** [comment]
> hey, i don't think you are supposed to add the charge point id to the central system url as it is the case in your screenshot. yes, it is required to be there, but i think charging station software might add it automatically.
> 
> i imagine that the url, which the station will use to connect, in your case contains the id twice, e.g. `ws://.../1A30.../1A30...`

Thanks for taking a look. It might be that simple. I'll make the change and report back. 

Thanks!

**Comment by retrocoder-78** [comment]
Yup, that was the problem. Heartbeat received and it's all connected through SteVe. Thanks goekay for taking a look. Really appreciate your time!
