### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by kevingkday** [RWTH-i5-IDSG/steve#381]
I'm familiar with OCP-J-CP Simulator which was posted in here a couple of years ago, but was wondering if anyone is aware of another simulator that may have been developed since then that works well with Steve.

**Comment by gabriel1lima** [comment]
I would like to know too

**Comment by goekay** [comment]
hello, except the ones posted in https://github.com/RWTH-i5-IDSG/steve/issues/53, i don't know any other.

i am closing this issue, such that we have one go-to location (the previous thread) for this type of discussion and new discoveries. i hope for your understanding.
