### ISSUE TITLE
How to change login / password after compilation?

### ISSUE THREAD

**Issue by DeltaVetal26** [RWTH-i5-IDSG/steve#387]
Hi,

Before compiling Steve, it was possible to specify settings in the configuration file, including the username and password.

As far as I understood, this only works before compilation.
Now I have a task to change the login and password.
I found the "user" table in MySQL, but there was no data there.

**Questions:**
1) How can I change the password in the compiled version?
2) Is it possible to create multiple accounts to access Steve panel?

Thank you!

**Comment by csamsel** [comment]
1. To set the the login username and password you have to rerun maven - correct.
2. No

**Comment by DeltaVetal26** [comment]
@csamsel ,

Thank you for the answer! Ok.

**Comment by goekay** [comment]
> I found the "user" table in MySQL, but there was no data there.

i want to clarify that this user table has nothing to do with the user of steve (for ex. charging station manager) who has to login to use the web interface. the definition of this user is the holder of an rfid card (ocpp tag).

**Comment by dulaimingming** [comment]
Hello, why can't I connect to STEVE, and what does the authkey mean?

**Comment by DeltaVetal26** [comment]
Hello @dulaimingming,

If you are talking about Steve configuration (main.properties file), then there is no such thing. AuthKey - authorization key. Where exactly did you find it?

**Comment by dulaimingming** [comment]
I can connect!&nbsp; Thank you for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RWTH-i5-IDSG/steve"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 中午1:42
收件人:&nbsp;"RWTH-i5-IDSG/steve"<steve@noreply.github.com&gt;;
抄送:&nbsp;"847970161"<847970161@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RWTH-i5-IDSG/steve] How to change login / password after compilation? (#387)





 
Hello @dulaimingming,
 
If you are talking about Steve configuration (main.properties file), then there is no such thing. AuthKey - authorization key. Where exactly did you find it?
