### ISSUE TITLE
There is no communication with the JSON 1.6 Setec charger

### ISSUE THREAD

**Issue by Kaniiisek** [RWTH-i5-IDSG/steve#393]
Hello. I'm trying to connect my Setec 20kW charger with Steve version 3.0.2 to a Raspberry for the first time.
If I enter the destination address with the charger ID into the charger, then in my case:
ws: //10.109.0.XXX: 8080 / steve / websocket / CentralSystemService / CBI-15xxxxxxxxx
Should I automatically contact Steve on raspberry and start communicating?
I tried Simple OCPP 1.6 Chargebox Simulator and it went fine.
Is there something I'm doing wrong?

**Comment by goekay** [comment]
hi, please look at a similar issue: https://github.com/RWTH-i5-IDSG/steve/issues/376

**Comment by Kaniiisek** [comment]
YES !!! It helped. Thank you very much. I'm really happy now.

**Comment by csamsel** [comment]
@goekay seems to be common pitfall, maybe we should slightly rephrase the field name in the GUI?

**Comment by goekay** [comment]
@csamsel i am not sure what part of the GUI you mean, but i think adjusting readme might be enough: https://github.com/RWTH-i5-IDSG/steve#add-a-charge-point
