### ISSUE TITLE
STEVE logo change ?

### ISSUE THREAD

**Issue by Kaniiisek** [RWTH-i5-IDSG/steve#398]
Hello, 
Is there any way to put your logo instead of or next to STEVE?
For example, I would need to display my contact information in the image on the main page next to or instead of the STEVE logo.

**Comment by goekay** [comment]
hello,

you can replace/modify the images here: https://github.com/RWTH-i5-IDSG/steve/tree/master/src/main/resources/webapp/static/images

**Comment by goekay** [comment]
i consider this issue resolved and therefore close it.
