### ISSUE TITLE
Heartbeat Interval and Data Consumption

### ISSUE THREAD

**Issue by GRangaRao** [RWTH-i5-IDSG/steve#406]
Hello Everyone,

Want to understand whether device Data Consumption can be controlled/reduced with steve settings?
In my case SIM consumes bulky data in a given day. Changing Heartbeat Interval is not having dramatic impact
on the data consumption

Thank You
Rao

**Comment by goekay** [comment]
steve does not provide such a functionality. i am not sure ocpp spec does either. maybe the configuration of your charge station has something related, i don't know.

you probably don't want to reduce communication related to actual usage of station (transactions, meter values, reservation etc.). the status updates might be a problem if implemented inefficiently by the station software. for eample, a simple solution would be sending 'available' messages every x seconds or x minutes redundantly. but the status does not change that often does it? i can imagine this producing a lot of unnecessary overhead. therefore, a more proper implementation would be sending these messages based on actual events, such as if actually the status changed. but all of this is station-specific.
