### ISSUE TITLE
Add missing / in nginx sample 

### ISSUE THREAD

**Issue by manitu-opensource** [RWTH-i5-IDSG/steve#451]
Currently there is a

`proxy_pass http://192.168.1.100:8080/steve/websocket/CentralSystemService;`

as sample for the `/steve/websocket/CentralSystemService` location.

This will fail if the OCPP client (e.g. KEBA P30) does not auto-add a slash (/) at the end before inserting the occp station id (when using Websocket/JSON).

Therefore we recomment to use

`proxy_pass http://192.168.1.100:8080/steve/websocket/CentralSystemService/;`

This should fit all ocpp clients as nginx is intelligent enough to "auto-fix" double slashes if some client  sends double-slashes in the original url.

You should update the faq to save others from wasting time.

**Comment by csamsel** [comment]
I don't think rerwriting the URL during the proxy'ing is a good idea. The charging station should then be configured with a base url including a / at the end.

**Comment by goekay** [comment]
agree with @csamsel. his suggestion looks good to me. it feels wrong to modify steve for some station's failure.
