### ISSUE TITLE
IdTagInfo does not work properly

### ISSUE THREAD

**Issue by TarikAkyuz** [RWTH-i5-IDSG/steve#453]
A screenshot from OCPP Tag Overview:
![steve_ocpp_tags](https://user-images.githubusercontent.com/32031307/100324027-ac4af600-2fd7-11eb-9592-8f530279ca34.png)

If ExpiryDate / Time is empty, it sends idTagInfo incorrectly. It should not be sending expiryDate field, but it sends a near time value.
When I start RemoteStartTransaction in OCPP v1.6, I can get the log below from my side.

`D: Ocpp Websocket : Message Received [2,"1b504468-1ba9-4c70-a7eb-d4759cb4ddbc","RemoteStartTransaction",{"connectorId":1,"idTag":"testTag04"}]
D: Ocpp Websocket : Send Message  [3,"1b504468-1ba9-4c70-a7eb-d4759cb4ddbc",{"status":"Accepted"}]

D: Ocpp Websocket : Send Message  [2,"khyk3ywv27v6q5h50mcj","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing"}]
D: Ocpp Websocket : Message Received [3,"khyk3ywv27v6q5h50mcj",{}]

D: Ocpp Websocket : Send Message  [2,"khyk3z43ujfkuznjz","Authorize",{"idTag":"testTag04"}]
D: Ocpp Websocket : Message Received [3,"khyk3z43ujfkuznjz",{"idTagInfo":{"status":"Accepted","expiryDate":"2020-11-26T09:10:09.675Z"}}]`  ======> testTag04 is infinite time but sending expirydate.

**Comment by goekay** [comment]
on the settings tab/page of steve, you can control this behaviour with the "hours to expire" field. quote from the page:

> The value 0 disables this functionality (i.e. no expiry date will be set).
