### ISSUE TITLE
Question: Is it possible to edit tables in mySQL

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#458]
I would like to add columns to the connector_meter_value table. Is this possible without it creating problems with communication between Steve and the Chargeboxes

**Comment by goekay** [comment]
it is possible. make sure that the columns are nullable though (because of the existing rows).

**Comment by rdc-Green** [comment]
Sorry Sevket, yes it’s closed. Thanks again for your help.

Sent from my iPhone

On 11 Dec 2020, at 19:27, Sevket Gökay <notifications@github.com> wrote:

﻿

Closed #458<https://github.com/RWTH-i5-IDSG/steve/issues/458>.
