### ISSUE TITLE
Standard Configuration Key Name HeartbeatInterval mismatch.

### ISSUE THREAD

**Issue by nuno407** [RWTH-i5-IDSG/steve#46]
When calling GetConfiguration requesting the HeartbeatInterval the Key Configuration name is HeartBeatInterval. The OCPP v1.6 correct key name is HeartbeatInterval.

PS: should I create a new issue for each new identified issue?

Thank you,
Nuno

**Comment by JavaIsJavaScript** [comment]
Made a Pull Request #47 for this.
