### ISSUE TITLE
pom.xml wrong version ?

### ISSUE THREAD

**Issue by EagleFlyFree** [RWTH-i5-IDSG/steve#470]
Shouldn't the pom.xml have the correct version ?
Steve Tag:    steve-3.4.4
pom.xml:   <version>3.4.3</version>

**Comment by goekay** [comment]
good catch. it is only a labeling mistake on my side, though. i will bump the version in pom.xml and point the release to the new commit. releases on github are nothing more than tagging the state of the repository based on a commit. therefore, feature-wise nothing changes.

**Comment by EagleFlyFree** [comment]
After git pull, I noticed that files changed, but the "about" still was reporting the old version and saying that there was a new version. I manually updated the pom.xml.
Thanx for the fast response :)
