### ISSUE TITLE
OCPP IDTags expiry date does not match the configuration in the Steve portal

### ISSUE THREAD

**Issue by nuno407** [RWTH-i5-IDSG/steve#48]
I have the following OCPP ID Tags:
![tags](https://user-images.githubusercontent.com/11352538/37920150-00efdd8a-311e-11e8-9584-7c43ebb5a52b.png)
And the SendLocalList command has the following output:

    Received: [2,"1f762142-f659-4a2a-a278-5148f00921b3","SendLocalList",{"listVersion":9,"localAuthorizationList":[{"idTag":"user","idTagInfo":{"expiryDate":"2018-03-26T16:44:14.689Z","status":"Accepted"}},{"idTag":"user1","idTagInfo":{"expiryDate":"2018-03-26T16:44:14.689Z","status":"Accepted"}},{"idTag":"user2","idTagInfo":{"expiryDate":"2018-03-26T16:44:14.689Z","status":"Accepted"}}],"updateType":"Full"}]

What could be the problem?
Thank you,
Nuno

**Comment by goekay** [comment]
are you living in a country with utc+1 timezone?

**Comment by nuno407** [comment]
Yes. But the expiry date year does not match anyway

**Comment by goekay** [comment]
the thing is, steve, the java application, is set to use UTC as time zone. if your database's timezone varies from that, during the reading/writing such results might occur.

**Comment by goekay** [comment]
on the other hand, the LocalAuthorizationList message is not wrong. "16:44:14.689Z" denotes the time in UTC (because of "Z" as suffix), which translates to 17:43 (after rounding) in your time zone. so.. i don't get what the issue is here?

**Comment by nuno407** [comment]
Ok. Then the solution is to use UTC timezone in the database also?
Thank you for the help.

**Comment by goekay** [comment]
as a best practice: steve time zone == mysql time zone

but i do not see any problem with the LocalAuthorizationList mesasage.

**Comment by goekay** [comment]
ah, i know what you mean, the date sent in LocalAuthorizationList does not match the actual expiry date from database. this was to prevent a charging station to read from local/cached white list all the time, if for example the expiry is 5 years from now, and trigger it to ask Steve for the actual, up-to-date authorization status. in the settings tab, you can see an Expiration setting. it controls the time window for caching local id tags.

**Comment by goekay** [comment]
maybe it's time to rethink whether this limiting/strict behaviour is necessary...

**Comment by nuno407** [comment]
Hi @goekay,
Sorry for the not so fast response. But Yeap I think you fixed the issue. 
Thank you! :smiley:
