### ISSUE TITLE
Remote start transaction without manually filling the form

### ISSUE THREAD

**Issue by mathief123** [RWTH-i5-IDSG/steve#491]
Hi.

First of all, thanks for your amazing job with SteVe ocpp.

Im trying to make a android app that would let me start a charger manually, so, is there a way to fill the remote start transacción form without filling the form manually? I have SteVe installed and it works, but only if i fill the data manually.

Thanks in advance and sorry for my english, as its not my first languaje.

**Comment by goekay** [comment]
hello, thanks for the kind words.

steve does not provide an api to control the operations. it only has the web pages.

however, this request pops up from time to time, and there are people who (i think) successfully did stuff like this. i would suggest to search the issues.

**Comment by goekay** [comment]
closing this issue due to its inactivity.
