### ISSUE TITLE
Running SteVE in Docker at Synology NAS (DS220+ - DSM 6.2.3)

### ISSUE THREAD

**Issue by Chillkroete1206** [RWTH-i5-IDSG/steve#502]
I want to start SteVE in Docker at Synology NAS (DS220+ - DSM 6.2.3) environment.

I follow the proceeding:
- Import new container from steve-steve-3.4.4.tar.gz file
- Start Image in Docker (visual environment)
- In properties I insert "docker-compose up -d" in execution command (German Version: "Ausführungsbefehl").

I receive this error:
`Start container steve-31 failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"docker-compose\\\": executable file not found in $PATH\": unknown"}.`

Can you tell me what am I doing wrong? Sorry for very few experience with Docker ;)
Thanks for your assistance!

**Comment by goekay** [comment]
the exception mesage is clear: it seems like that you do not have `docker-compose` executable in your path, therefore the command is unknown.

please use google to investigate your issue further, because it is not related to steve. and therefore i am closing this issue.
