### ISSUE TITLE
SteVe using Ubuntu 20.04

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#504]
Will SteVe work on Ubuntu 20.04. 

We're looking to install virtualmin, which requires the latest version of Ubuntu to run or we can install cPanel if that works with SteVe?

**Comment by csamsel** [comment]
I have not personally tested it, but i dont see any reason why it would not.

**Comment by goekay** [comment]
since @rdc-Green reacted with thumbs up, i consider this question answered and therefore closing it :)
