### ISSUE TITLE
How to build and run this project in eclipse

### ISSUE THREAD

**Issue by Droidverine** [RWTH-i5-IDSG/steve#505]
I'm able to compile and run the project using the commands mentioned in the readme, but I wanted to open the project in eclipse and run it from there. The error issue I'm getting is with the "Flyway".

**Comment by goekay** [comment]
sorry, not familiar with eclipse _anymore_, since i use intellij. i switched because of issues like this years ago.

**Comment by Droidverine** [comment]
> sorry, not familiar with eclipse _anymore_, since i use intellij. i switched because of issues like this years ago.

Thanks for your response, can you please tell me the steps required to set this project up on intellij?

**Comment by goekay** [comment]
the steps are the same as every java project using maven. google is your friend ;)
