### ISSUE TITLE
OCPP 2.0(.1) Support

### ISSUE THREAD

**Issue by andle** [RWTH-i5-IDSG/steve#513]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve
SteVe does not surrently support OCPP 2.0.
...

#### Describe the solution you'd like
OCPP 2.0 support: might have to be a whole new SteVe!?!
...

#### Describe alternative solutions or features you've considered 
Sticking with 1.6 for now :(
...

#### Additional context
I know this would be a huge undertaking, but I just wanted to put the feelers out and see if this is something the SteVe developers have considered. What do you think? Is there something already in progress that I am unaware of?
...

**Comment by goekay** [comment]
here is the same question from last summer: https://github.com/RWTH-i5-IDSG/steve/issues/373

there has been no progress in this regard. i will implement ocpp 2.0 some time in the future, but cannot say when.

**Comment by andle** [comment]
Thanks for the quick response. And thanks again for SteVe! I'll close this issue.

**Comment by kharsch1337** [comment]
Are the any updates to OCPP 2.0(.1) for steve ?

**Comment by goekay** [comment]
@kharsch1337 it will probably come in 3rd quarter of 2026.
