### ISSUE TITLE
Question about the content of the error: "has thrown exception, unwinding now" (Probably not a bug)

### ISSUE THREAD

**Issue by DeltaVetal26** [RWTH-i5-IDSG/steve#514]
**Note:** This issue may not be related to the Steve himself. We are trying to figure it out, the only step is to ask you.

In the summer I created a topic where I talked about a script that allows you to remotely send commands to Steve's web control panel.

https://github.com/RWTH-i5-IDSG/steve/issues/338

All is well, this script works completely with Steve on the JSON version of OCPP.

Recently I was approached by a person whose station works on SOAP.

The only thing that could be done with this script and SOAP version is to get the current state of the connector.
All other commands are not processed.
Steve logs contain the following:

![108080153-d9a3bf00-706f-11eb-8b78-2ac674e8deb2](https://user-images.githubusercontent.com/16554245/108515654-6059d580-72d6-11eb-817e-955420d617fc.png)

Could you help explain the meaning of this error?
Is it somehow related to the station?

```
SteVe Version     : 3.4.4
Operating system  : Ubuntu
JDK               : 11.0.10
Database          : 5.7.33
```

Thank you!

**Comment by goekay** [comment]
hey, 

regarding soap: steve does not know the url of the station to send the message to. `endpoint_address` in table `charge_box` is not set. therefore, this exception happens.

regarding json: there has to be an active/open websocket session to this station. otherwise, you would see an exception with `No session context for chargeBoxId ...`

**Comment by goekay** [comment]
more info about `endpoint_address`: every time a station interacts with steve (message flow: station -> steve), one of the headers contains this field. steve will update it, if it is set. apparently it is not.

**Comment by DeltaVetal26** [comment]
Hi @goekay,

Thank you for the answer!

Ok, I will try to add an endpoint (soon).
I will report on the result.

**Comment by goekay** [comment]
hey @DeltaVetal26, i came across this issue again while i was cleaning up the open issues. what is the status? the problem seems to be about your project that acts as a client to steve. can we close this one?

**Comment by DeltaVetal26** [comment]
Hi @goekay, Yes, the issue has been resolved. That was my fault.

Sorry for not answering for so long.
