### ISSUE TITLE
 Starting got FAILED

### ISSUE THREAD

**Issue by vasya00044** [RWTH-i5-IDSG/steve#527]
I set up and configured SteVe. Got a message "BUILD SUCCESS"
I start the application run
# java -jar target/steve.jar
But Starting got FAILED! 

I attach the log file [log.txt](https://github.com/RWTH-i5-IDSG/steve/files/6095068/log.txt)

Help me!!!

#### Specifications
```
SteVe Version     : 3.4.4
Operating system  : ubuntu 1.18.04
JDK               : 11.0.10
Database          : MariaDB 10.3
```

**Comment by goekay** [comment]
we had this already multiple times: #326 #139 #318

**Comment by vasya00044** [comment]
thank. problem solved!!!!!!
