### ISSUE TITLE
AES decrypt password

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#562]
I've run 'Get Diagnostics', which downloads an aes file. I've tried to open using AES Crypt, but i don't have a password. Is this stored in SteVe somehwere?

**Comment by csamsel** [comment]
No, the file is provided by the charge point and just forwarded by. I guess the manufacturer don't want you to look at it.

**Comment by goekay** [comment]
i consider this issue resolved due to its inactivity, and am closing it.
