### ISSUE TITLE
Websocket Basic Auth

### ISSUE THREAD

**Issue by andle** [RWTH-i5-IDSG/steve#565]
#### Checklist

- [ x] I checked other issues already and found no answer
- [ x] I checked the documentation and found no answer
- [ x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve
Some charge points use basic auth for web socket connections. I can't seem to find configuration for using basic auth.

#### Describe the solution you'd like
It would be nice to have web socket basic auth (username, password). I think they could be put in configuration file at build, or maybe have field in Web app to set.

#### Describe alternative solutions or features you've considered 
Not using basic auth?

**Comment by goekay** [comment]
it is not implemented. please refer to #100 and #128.
