### ISSUE TITLE
Adding charging profiles is unintuitive

### ISSUE THREAD

**Issue by barsnick** [RWTH-i5-IDSG/steve#580]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.4 (same issue on git master 10f88e25908b19f21b9de56d617af0479e4c9728)
Operating system  : Linux 5.11.20, Fedora 33 (kernel-5.11.20-200.fc33.x86_64), running inside VirtualBox
JDK               : OpenJDK 11.0.11.0.9 (java-11-openjdk*-11.0.11.0.9-2.fc33.x86_64)
Database          : MariaDB 10.4.19
```

#### Expected Behavior

Useful button namings and assistance through messages.

#### Actual Behavior

Somewhat confusing.

#### Steps to Reproduce the Problem

  1. In SteVe's web interface, select Data Management -> Charging Profiles -> Add New (this is intuitive)
  2. Enter some data and note that there are two "Add" buttons.
  3. Press the blue "Add" button. See the message: "Error while trying to add a charging profile: * must not be empty". What must not be empty?
  4. Fill all fields, press "Add" again, and note that something still should not be empty.

#### Additional context

I suggest:
- Make sure that the message says that it's missing a Schedule Period.
- It might be useful to know which fields are optional (but that task may be up to the user).
- Name the two buttons differently: "Add schedule period", "Add this charging profile", or something like this.

On git master, I additionally get a backtrace. I will open a separate issue for that.

Thanks!

**Comment by goekay** [comment]
thanks for the report. your suggestions are implemented!
