### ISSUE TITLE
OCPP1.5 meter units "Volt","Amp" not accepted

### ISSUE THREAD

**Issue by chuck-h** [RWTH-i5-IDSG/steve#59]
Between v1.5 and v1.6 there was a subtle change in the UnitOfMeasure type: "Volt" and "Amp" were shortened to "V" and "A". The Server15to16Impl converter needs to take this into account.

**Comment by goekay** [comment]
good catch, thanks! i appriciate your PR but i think i have another idea how to implement it since string search/replace (even with regex) might be a little fragile and problematic in future.
