### ISSUE TITLE
Keystore with multiple certificates

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#592]
We are trying to implement Cloudflare with Virtualmin on Ubuntu 20.04 using steve 3.4.4. We have successfully set it up with http, but we would like to enable wss, which means having https set as true in the main.configuration file (we had this setup working successfully in our old server with webmin (not virtualmin). If we do this we get the following error when restarting steve:

```
[ERROR] 2021-05-20 22:37:14,884 de.rwth.idsg.steve.SteveProdStarter - Exception happened
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.s>
```

We have the couldflare certs saved in home/user/CloudflareCertificates/

We have switched off SSL in Virtualmin

**Comment by goekay** [comment]
thanks for the report. it looks like the usage of `SslContextFactory` is deprecated in newer versions of jetty in favour of `SslContextFactory$Server`.

other sources that report the same:
- https://opennms.discourse.group/t/jetty-with-ssl-throws-error-with-keystores-with-multiple-certificates-are-not-supported/1489
- https://github.com/OpenNMS/opennms/pull/3106
- https://issues.apache.org/jira/browse/NIFI-7730

will migrate to the new class in ASAP.
