### ISSUE TITLE
How to authorize a transaction without an OCPP IdTag

### ISSUE THREAD

**Issue by Dan-27** [RWTH-i5-IDSG/steve#594]
Hi, I'm planning to use an EV charger without any RFID card. Can SteVe authorize the start of a transaction without any OCPP idTag?

**Comment by goekay** [comment]
if the business/use case does not require authorization, the ev charger should not ask steve about auth of an idtag.

> Can SteVe authorize the start of a transaction without any OCPP idTag?

steve does not auth the start of transactions. ev chargers _report_ the starts and stops of transactions. 

that being said, there is not feature flag in steve to enable _accepting every idtag from an auth request_ (which would have addressed your use case... indirectly).
