### ISSUE TITLE
timestamp returned is inconsistent with the OS time

### ISSUE THREAD

**Issue by henrywah196** [RWTH-i5-IDSG/steve#62]
Please see screenshot
client send a bootnotification the response contains the currenttime, which is inconsistent with the local OS time.

![capture](https://user-images.githubusercontent.com/23351768/39788741-9f505106-52e0-11e8-8d47-1a220341dbda.png)

**Comment by csamsel** [comment]
Because it's always in UTC

**Comment by goekay** [comment]
@csamsel is right. however, you can change it in https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/SteveConfiguration.java#L25
