### ISSUE TITLE
Übersetzung einzelner Beschreibungen 

### ISSUE THREAD

**Issue by LadesaeulenBetreiber96450** [RWTH-i5-IDSG/steve#635]
Hallo an alle,

Ist es möglich die HTML-Oberfläche des Steve Servers in eine andere Sprache zu übersetzen.
Wäre dankbar wenn es Lösungsvorschläge geben würde.

Gruß Dominik

**Comment by goekay** [comment]
yes, it is. you can google for "internationalization spring" to see the possibilities and guides. this would mean converting every bit of english text we have right now into a variable whose actual value (depending on locale/language) needs to be stored in a distinct messages file.

i see it as a big undertaking and am not sure about its cost-to-benefit ratio.

**Comment by csamsel** [comment]
a different approach would be to just translate the jsp pages inside the WEB-INF directory for their personal use.
