### ISSUE TITLE
Transaktionen werden nicht angezeigt 

### ISSUE THREAD

**Issue by LadesaeulenBetreiber96450** [RWTH-i5-IDSG/steve#637]
Hallo,

seid einiger Zeit zeigt der Steve-Server keine Transaktionen mehr in der Weboberfläche an.
Einige Lösungen habe ich schon probiert :

1. Raspberry Pi 3 auf 4 gewechselt
2. Einige verschiedene Versionen von Maria-DB installiert
3. Raspberry Pi Image von Lite auf Full

Leider haben alle Lösungsansätze keinen Erfolg gebracht !
Vielleicht habt ihr ja noch einen Vorschlag.

Im Anhang das Log-File 

Gruß
Dominik

Log File :
[Log-
[Log-File.txt](https://github.com/RWTH-i5-IDSG/steve/files/6941500/Log-File.txt)
File.txt](https://github.com/RWTH-i5-IDSG/steve/files/6941478/Log-File.txt)

**Comment by goekay** [comment]
hi, please use english for everyone to be able to participate in the discussion, and future readers to be able to understand the communication.

the logs indicate that the charging station is sending a meter value message referencing a transaction with id. for example:

```
[INFO ] 2021-08-05 20:08:15,680 de.rwth.idsg.steve.ocpp.ws.WebSocketLogger - [chargeBoxId=Suec, sessionId=063e7762-461c-7670-aafb-5b34e81241f6] Received: [2,"3","MeterValues",{"connectorId":1,"transactionId":14,"meterValue":[{"timestamp":"2020-12-28T09:51:50Z","sampledValue":[{"value":"3.743","context":"Sample.Periodic","measurand":"Energy.Active.Import.Register","location":"Outlet","unit":"kWh"}]}]}]
```

the transaction 14 is unknown to steve, meaning the charging station did not send the information about this transaction (StartTransaction message) before sending a MeterValues message. therefore, the database refuses to process this.
