### ISSUE TITLE
Change Timezone 

### ISSUE THREAD

**Issue by LadesaeulenBetreiber96450** [RWTH-i5-IDSG/steve#638]
Hello,
I need help, how can I change the time zone from UTC to UTC + 2 in the Steve server.

And how in the Maria DB?

Thank you
Dominik

**Comment by goekay** [comment]
hi,

you need to change the text "UTC" [in this line](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/SteveConfiguration.java#L46) to your time zone. afterwards, you need to run compile and build the project by running `mvn package` on your terminal.

for mariadb, google is your friend ;)
