### ISSUE TITLE
Implementation with the server

### ISSUE THREAD

**Issue by belljohan3** [RWTH-i5-IDSG/steve#644]
I built the app stev.jar but i can't start it. Can someone help me out ? we can chat on Telegram. Here is my ID: @johanbell. May be a problem with a server ?
[steve.log](https://github.com/RWTH-i5-IDSG/steve/files/6987826/steve.log)

**Comment by goekay** [comment]
steve uses the time zone of utc. your mysql instance should use utc as well. this is not the case and the errors in the log file indicate this problem.

**Comment by belljohan3** [comment]
Ok ! @goekay. i'm using mariaDB. How can i set it please ? Where can i find the MySQL instance ?

**Comment by goekay** [comment]
i added the info to our FAQ since this issue comes up a lot: https://github.com/RWTH-i5-IDSG/steve/wiki/FAQ#how-to-fix-the-exception-mysql-and-java-are-not-using-the-same-time-zone

if you are not familiar with these concepts, i would suggest googling.

**Comment by belljohan3** [comment]
OKay !
THanks

**Comment by belljohan3** [comment]
Is it here that we have to change the time zone?

![UTC](https://user-images.githubusercontent.com/50105980/129474620-e3244cce-51af-44d5-9c1f-e9b327be15f8.PNG)

**Comment by goekay** [comment]
please do not change the time zone of steve itself, but the time zone of mysql/mariadb. in my message above and in the faq entry i hinted at that. why are you still trying to change the time zone of steve?

changing the time zone of steve will cause issues, since many charging stations cannot handle time zones properly.

**Comment by belljohan3** [comment]
Am i on the good way my friend ?

![database](https://user-images.githubusercontent.com/50105980/129474950-29447d78-5eb8-4702-b970-f9a6ad3881e1.PNG)

**Comment by goekay** [comment]
i consider the issue resolved, and am closing it.
