### ISSUE TITLE
Upgrade procedure

### ISSUE THREAD

**Issue by mikgthub** [RWTH-i5-IDSG/steve#645]
I am using Steve to learn OCPP. Thank you for the excellent project.
Which is the best procedure to upgrade from 3.4.4 to 3.4.5 ?
Installation is on Ubuntu 20.04 esxi VM

**Comment by goekay** [comment]
there is no need for special attention for upgrading. just downloading the source with release, compile&build and run it.

or better: i would suggest to clone the git repository and always keep it around. when we make a release, it is nothing more than tagging a commit. in these cases you can pull and check-out the release commit, build and run the project.

**Comment by mikgthub** [comment]
done. many thanks.
