### ISSUE TITLE
Remote Stop Transaction

### ISSUE THREAD

**Issue by momoko-squid** [RWTH-i5-IDSG/steve#651]
Upon issuing a Remote Stop Transaction request from Steve, my ChargePoint status goes to "Authorized".
Shouldn't status be transaction stopped?

```
SteVe Version        : 3.4.4
Operating system  : Ubuntu 20.04.02 LTS
JDK                       : openjdk 14
Database              : mariadb 10.5.11
```

...

**Comment by goekay** [comment]
> Upon issuing a Remote Stop Transaction request from Steve, my ChargePoint status goes to "Authorized".

i am not sure what you mean with charging status going to authorized. there is not status called authorized.

> Shouldn't status be transaction stopped?

steve just sends a request to stop the transaction. how the station reacts to this, is station's business.

are you sure that this is a steve issue?
