### ISSUE TITLE
2-Tier Connection Support in Steve 

### ISSUE THREAD

**Issue by HARSHAL93** [RWTH-i5-IDSG/steve#660]
Appreciated to all efforts to provide great platform.
I have implemented java application with provided code and everything is working as expected.
As I am new in this domain only work experience in Embedded C with Hardware stuffs.
I am planning to add another one charging connector with same charge point  to make 2-tier charger point,it will be helpful to get support to know from where to start and what kind of changes are required in existing code.

**Comment by goekay** [comment]
hey, thanks for the kind words.

if i understand you question correctly, there are no changes necessary. steve supports multiple charging points, and also multiple connectors per charging point.

**Comment by goekay** [comment]
i consider this issue resolved.

**Comment by HARSHAL93** [comment]
Yes, Thanks
