### ISSUE TITLE
OCPP charge point (TELLUS 4120) keeps dropping communication to steve

### ISSUE THREAD

**Issue by rishabhmehandru** [RWTH-i5-IDSG/steve#666]
#### Checklist

- [ ] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...3.4.5
Operating system  : ...ubuntu debian
JDK               : ...
Database          : ...mysql 5.7
```

#### Expected Behavior
Connection with websocket maintained all the time. 
...

#### Actual Behavior
Connection to machines gets dropped.When physically machine interface is rebooted, connection is re-estabilished
...

#### Steps to Reproduce the Problem

  1. ...More than one charge point connected
  2. ...One just drops within a few hours
  3. ...

#### Additional context

...

**Comment by goekay** [comment]
how often do these drops occur? steve should not cause any connection drops. are you sure that steve's network is stable? are you sure that charging stations maintain a stable network connectivity? can you post any logs for more context?

**Comment by rishabhmehandru** [comment]
Yes, I think we need machine to machine SIM

**Comment by goekay** [comment]
> Yes, I think we need machine to machine SIM

i don't know how to start any investigation with this bit of information.

i assume that your problem is not because of steve, but other components. i cannot help you there.

**Comment by rishabhmehandru** [comment]
Hi

I switched to machine2machine SIM but I am still seeing dropping off of one of the chargers. Will you be willing to look at the log and help me figure out why the charger is dropping?

Best
Rishabh

**Comment by rishabhmehandru** [comment]
[steve.log](https://github.com/RWTH-i5-IDSG/steve/files/7316018/steve.log)

**Comment by rishabhmehandru** [comment]
Hi

Thank you so much for your help. I will investigate further on the machine
side to see why this could have happened.

Best
Rishabh
