### ISSUE TITLE
mysql.proc no longer exists in mysql version 8.0

### ISSUE THREAD

**Issue by ghamkhari** [RWTH-i5-IDSG/steve#67]
the `mysql.proc` table no longer exists in mysql version 8.0. See [here ](https://ocelot.ca/blog/blog/2017/08/22/no-more-mysql-proc-in-mysql-8-0/)for more details. 

Therefore, I couldn't execute below code: 

`GRANT SELECT ON mysql.proc TO 'steve'@'localhost' IDENTIFIED BY 'changeme';`

Does this make any issue?

**Comment by csamsel** [comment]
IIRC it's required for the JOOQ, the used database abstraction layer. We havent tested MySQL 8 it, but i have to assume that things will break.

**Comment by ghamkhari** [comment]
Instead of mysql, I used MariaDB and things are working properly.
