### ISSUE TITLE
Vehicle VIN querry for smart grid integration 

### ISSUE THREAD

**Issue by rishabhmehandru** [RWTH-i5-IDSG/steve#683]
#### Checklist

- [ ] I checked other issues already and found no answer
- [ ] I checked the documentation and found no answer
- [ ] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

...

#### Describe the solution you'd like
Is it possible to add VIN querry which uniquely identifies each vehicle to websocket handshake through Steve? That will allow direct authentication of the idTag if the VIN is registered with the tag.

is this in plan or if you have some idea about how to implement it that will help.
...

#### Describe alternative solutions or features you've considered 

...

#### Additional context

...

**Comment by goekay** [comment]
the idtag is an abstract term in the ocpp spec. it can be an rfid card tag, but it can also be a vin. it is just a string that identifies the user. in that respect, it is the charging station's responsibility to map a vin to idtag and use it in the ocpp operations. there is no changes necessary in steve.
