### ISSUE TITLE
Setting and getting injected current to EV

### ISSUE THREAD

**Issue by ghamkhari** [RWTH-i5-IDSG/steve#69]
1) Which menus of steve should I use to set the `Maximum Current` that my charger point injects to EV? 

2) Which menus should I use to measure the `Maximum Current` that is set for my charger point? 

3) Which menus should I use to measure the `Current` that my charger point is injecting to EV?

**Comment by goekay** [comment]
i believe these are features included in the Smart Charging profile of ocpp 1.6. as indicated on the homepage, steve currently does support Smart Charging (not implemented). see discussion [here](https://github.com/RWTH-i5-IDSG/steve/issues/44).

**Comment by goRaspy** [comment]
Depending of manufacturer implementation. You can probably setup some parameters by "custom" change configuration. You can try to access to parameters list by sending an empty "get configuration" to the charge point.
