### ISSUE TITLE
Compilation error with END header not found

### ISSUE THREAD

**Issue by Loop-Donsky** [RWTH-i5-IDSG/steve#690]
Replica of issue #130 (CLOSED)

I assume this means the nexus servers are down again?

Is there something we can host as a backup for instances like this?
#### Checklist

- [X] I checked other issues already, but found no answer/solution
- [X] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.2
Operating system  : Amazon Linux
JDK               : openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
Database          : MariaDB
```

#### Steps to Reproduce the Problem

  1. run `mvn package` or `mvn clean package`
  2. - Build Fails -

#### Additional context

...

**Comment by goekay** [comment]
due to lack of further discussion, i consider the issue resolved. i am closing it.
