### ISSUE TITLE
ConnectorStatus shows rejected CS connectors even as available

### ISSUE THREAD

**Issue by nh38** [RWTH-i5-IDSG/steve#691]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve
When setting an charging station to rejected the connector IDs remain in the ConnectorStatus page as "Available".

#### Describe the solution you'd like
If a charging station is set to rejected the corresponding connectors should not be shown in the ConnectorStatus overview.

#### Describe alternative solutions or features you've considered 
Option to keep the transaction data after removing a charging station.

#### Additional context
Some background information:
We pulicated the ConnectorStatus view to the Users so that they can check current charge point status for themselves. Additionally we renamed the charging station and want to keep it as REJECTED due to transactions in database but the connectors are still shown as Available.
We want to keep the transaction data in database of rejected/removed charging stations in order to analyse and evaluate past transactions.

Thanks in advance!

**Comment by goekay** [comment]
thanks for pointing this out. it is a nice feature request (or... actually an edge case that was not handled properly).

even though we have the registration status information in database, we are currently not considering it to filter out connector status information of rejected stations. i will work on this.

> Option to keep the transaction data after removing a charging station.

transaction data will not be affected.

**Comment by goekay** [comment]
the latest ocpp version we support (version 1.6) determines 3 registration status values: Accepted, Pending, Rejected.

Accepted and Rejected are self explanatory. Definition of Pending: "Central System is not yet ready to accept the Charge Point. Central System may send messages to retrieve information or prepare the Charge Point."

it seems like the right thing to do to allow connector status information of only Accepted stations. i am developing the logic accordingly.

**Comment by goekay** [comment]
hey @nh38,

the referenced commit and PR address the issue. i hope it fully covers your problem. you can reopen this otherwise.
