### ISSUE TITLE
connector_pk numbers not increasing by one

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#697]
Hi,

I have a few charge points added to my system. When I add a new one, instead of the connector_pk increasing by an increment of 1, it increases by a random number (it seems) by about 200,000.

This doesn't appear to cause any issues yet, but I was wondering if this was a known issue (if it is even an issue) or if there is some way to fix it so that each time a connector is added it just increments by 1.

Thank you
Richard

**Comment by goekay** [comment]
are you sure about this? it's hard to say from outside why it is like this, but it should not be like that.

**Comment by rdc-Green** [comment]
i'm sure @goekay please see screenshot below of some connector_pks in cronological order:

![image](https://user-images.githubusercontent.com/73591141/140882672-b5387ad4-a839-4876-85f1-72862ea78951.png)

Is there any part of the code you could suggest I take a look at to see why it is doing this?

**Comment by goekay** [comment]
this field is managed by database since it is a primary key with auto increment. we can see from the screenshot that the PKs do not increase by 200k. 

the only explanation i can give: there are gaps between the values because you probably deleted some charging stations that had connectors that were deleted as well.

**Comment by rdc-Green** [comment]
Hi,

i was just approximating with the 200k. As you can see it goes from 609 to 3483 and then 3932 to 347093. I haven't deleted that many charging stations.

I will keep looking to see if i can find a reason. Thank you for takinig the time to get back to me.

**Comment by goekay** [comment]
> I haven't deleted that many charging stations.

maybe one station was misbehaving and therefore reported a lot of connectors to steve?

**Comment by rdc-Green** [comment]
i suppose there is no way of finding the misbeahving station!

**Comment by goekay** [comment]
you can look at the number of connectors per station:

```
select charge_box_id, count(*) as number_of_connectors
from connector
group by charge_box_id
order by number_of_connectors;
```

**Comment by rdc-Green** [comment]
I tried that, but i have between 2-3 depending if its dual socket or not.

**Comment by goekay** [comment]
i am closing this issue because there was no follow-up, and i doubt it is a fault of steve. @rdc-Green you can re-open it, if you have further info and evidence.
