### ISSUE TITLE
Limit access to web interface?

### ISSUE THREAD

**Issue by SmithD123** [RWTH-i5-IDSG/steve#701]
Hello,
My current implementation requires that the web socket connection be open to the internet. But I would greatly prefer that the web interface only be accessible from a few different IP addresses. My current ideas for solutions are:

• Running web socket and the web interface on separate ports. Allowing firewall blocking.
• Simply returning any unauthorized IPs a 401/403 HTTP code.
• Worst case outright disabling the web interface may be an option. I can make API calls and a simple app to call whatever is needed from the approved machines.

Is there any specific solution you think would be optimal? Looking at [this](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/JettyServer.java) file and a few google searches makes me think that redirecting/blocking unauthorized IPs may be the simplest solution but I am not entirely sure where to start implementing that.

Thank you

**Comment by shadsnz** [comment]
In my case, I handled this via policies on my external firewall.  I had one policy that restricted access based on country - you could use the same approach for allowing authorised IPs.   I also wanted to prevent external access to the web pages (steve/manager/ etc) and used a regex based policy to prevent access.  So externally you can access the webservices but not the web pages.  And we access the web side from our internal devices. 

We even went one step further and used another regex policy to only allow connections from chargers with authorised Charge Box IDs.

But, this is all dependant on the functionality available in your external firewall/router.
