### ISSUE TITLE
Server is not calling the extends class of AbstractAnnotationConfigDispatcherServletInitializer

### ISSUE THREAD

**Issue by ManjulaHonnappa1** [RWTH-i5-IDSG/steve#71]
Created a new class by extending 'AbstractAnnotationConfigDispatcherServletInitializer'.
But the container is not loading this class like 'SecurityConfiguration' class.

I assume some configuration to be done at 'SteveAppContext.java'

Please can you help on resolving this.

Thanks in advance.

**Comment by goekay** [comment]
without knowing the context and what you are trying to do, it's really hard for me to help you. you did not event fork this repo and work open source for me to look at it. do you have some spring experience? i think using `AbstractAnnotationConfigDispatcherServletInitializer` is outdated and there are newer approaches in recent spring versions (for example, we have no classes that extend it). we are not doing anything crazy with spring either. so... if you have some spring know-how, it should be pretty easy to modify steve.

having said that, this is not an issue or a problem related to steve. if you are extending the capabilities of steve, you are more or less on your own. the source code is open and there are some comments where i felt necessary. i hope they help.
