### ISSUE TITLE
After Update to 3.4.6 still 3.4.5 is shown in webinterface

### ISSUE THREAD

**Issue by RedPeace** [RWTH-i5-IDSG/steve#710]
Hi,

#### Checklist

- [x ] I checked other issues already, but found no answer/solution
- [x ] I checked the documentation and wiki, but found no answer/solution
- [x ] I am running the latest version and the issue still occurs
- [ x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.5 / 3.4.6
Operating system  : Ubuntu
JDK               : ...
Database          : MariaDB
```

#### Actual Behavior

i've downloaded and extracted 3.4.6.
Then replaced the main.properties

While compiling 3.4.5 is shown and the webinterface show 3.4.5 too.

Is it a bug or my fault?

#### Steps to Reproduce the Problem

  1. Download 3.4.6
  2. Extract
  3. Replace main.properties
  4. compile
  5. start

Regards!
Gero

**Comment by goekay** [comment]
it is my fault because i forgot to update the version string. fix incoming. however, it does not mean that the release is faulty.

**Comment by goekay** [comment]
thanks @RedPeace. the release is updated.
