### ISSUE TITLE
Log4Shell

### ISSUE THREAD

**Issue by TimothyHvr** [RWTH-i5-IDSG/steve#714]
Does the Log4Shell vunerability affect SteVe?
If so, should we take it down if the SteVe container on our VPS is exposed to the internet?

**Comment by goekay** [comment]
> Does the Log4Shell vunerability affect SteVe?

with [the latest release](https://github.com/RWTH-i5-IDSG/steve/releases/tag/steve-3.4.7) not anymore. if you use an older version, yes.

**Comment by leggler** [comment]
Is there an update procedure other than a complete re-install? And If yes, is there some documentation/blogentry etc. somewhere?
