### ISSUE TITLE
Noob question - read transactions and other data via webservice?

### ISSUE THREAD

**Issue by laxroth** [RWTH-i5-IDSG/steve#743]
Dear all,

is it possible to access the data stored in Steve using a webservice, does SteVe offer webservice? 
I would use jQuery Ajax to access data.
Any hints for me?

Best, laxroth

**Comment by skullmonkey911** [comment]
hi laxroth.
I guess no. I'm not aware of a soap or rest interface for clients accessing Steve.

Regards, Stephan

**Comment by goekay** [comment]
no, this is not possible at the moment.
