### ISSUE TITLE
404 http error

### ISSUE THREAD

**Issue by mamtamemoria** [RWTH-i5-IDSG/steve#750]
In which class signin (first page) is returned when request is made to 127.0.0.1:8080/steve/manager/home/I am getting http 404 error when creating a simple embedded jetty project.

**Comment by goekay** [comment]
hello, it's this one: https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/resources/webapp/WEB-INF/views/signin.jsp

**Comment by goekay** [comment]
due to lack of further discussion, i consider the question answered and close this issue.
