### ISSUE TITLE
Feature req: Add unknown ID cards

### ISSUE THREAD

**Issue by TechOverflow** [RWTH-i5-IDSG/steve#77]
Would it be possible to have the choice of adding an unknown card via a select field on the Add Tag page?

I know it can simply be copied and pasted, but this would be a nice helper.

**Comment by goekay** [comment]
unknown tags are already presented on the occp tags page (clicking the upper bar will toggle the table). please clarify if i understand this correctly: you don't want copy/paste these entries in another page, but want a button (or somethink like that) at that row the add that unknown tag? is my understanding correct?

**Comment by TechOverflow** [comment]
Correct. The same could be done for unknown chargepoints.
