### ISSUE TITLE
Directory URI

### ISSUE THREAD

**Issue by Pradhyu-21** [RWTH-i5-IDSG/steve#787]
What need to be placed in GET Diagnostics / Directory URI ?

**Comment by goekay** [comment]
the field location should reference a URI. 

from spec:
![Untitled-1](https://user-images.githubusercontent.com/3861031/159864897-2c7d0123-d09b-46eb-a40c-25afb00c1ab2.jpg)

**Comment by Pradhyu-21** [comment]
what to do if i want to directly download it from a browser interface ?

**Comment by goekay** [comment]
i guess you cannot do that. with the GetDiagnostics message, you are telling the charging station where it should upload the thing. after that the station controls the behavior and logic.

**Comment by Pradhyu-21** [comment]
ok got it
