### ISSUE TITLE
Compile Error with 3.4.9

### ISSUE THREAD

**Issue by kibeki** [RWTH-i5-IDSG/steve#795]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ steve ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 305 source files to /home/steve/steve-steve-3.4.9/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/ChargePointRepositoryImpl.java:[60,35] cannot find symbol
  symbol:   class ConnectorStatus
  location: package jooq.steve.db.tables
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/ChargePointRepositoryImpl.java:[60,1] static import only from classes and interfaces
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/OcppServerRepositoryImpl.java:[54,35] cannot find symbol
  symbol:   class ConnectorStatus
  location: package jooq.steve.db.tables
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/OcppServerRepositoryImpl.java:[54,1] static import only from classes and interfaces
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.219 s
[INFO] Finished at: 2022-04-04T16:43:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project steve: Compilation failure: Compilation failure:
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/ChargePointRepositoryImpl.java:[60,35] cannot find symbol
[ERROR]   symbol:   class ConnectorStatus
[ERROR]   location: package jooq.steve.db.tables
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/ChargePointRepositoryImpl.java:[60,1] static import only from classes and interfaces
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/OcppServerRepositoryImpl.java:[54,35] cannot find symbol
[ERROR]   symbol:   class ConnectorStatus
[ERROR]   location: package jooq.steve.db.tables
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/OcppServerRepositoryImpl.java:[54,1] static import only from classes and interfaces
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by goekay** [comment]
it looks like that the build process cannot access the database to generate some java sources/classes. this is the reason that the compiler cannot find some symbols.

please make sure that your db credentials are correct and that the db can be accessed.

**Comment by kibeki** [comment]
the db connection is the same as from the already installed version 3.4.8
I already doublechecked these credentials

**Comment by goekay** [comment]
i can compile the HEAD of the repo locally with java 11 and mysql 5.7, mysql 8 and mariadb 10.4.18. 

github actions (with different java versions and database flavours) can build as well: https://github.com/RWTH-i5-IDSG/steve/actions/runs/2071096809

so... i don't know how i can help you. i must assume that something is faulty in your setup. you did not communicate what java and mysql/mariadb version you are using. in fact, you actively skipped over the template and did not provide me any details and context.

**Comment by kibeki** [comment]
Hi Goekay,

what I want to do is to update my running 3.4.8 version to the latest 3.4.9. I followed the chapter "Configuration and Installation" from here https://github.com/RWTH-i5-IDSG/steve

I use MariaDB Server version: 10.3.34-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04 and openjdk 11.0.14.1 2022-02-08

I checked to connect to mysql with user steve@localhost. That worked fine.

**Comment by goekay** [comment]
the newly downloaded steve package will not have your customised main.properties file. it will come with the default configs from the HEAD of the repo. therefore, you need to copy from your version to the new one and rebuild the project.

see a similar issue: https://github.com/RWTH-i5-IDSG/steve/issues/794

**Comment by kibeki** [comment]
Already did that. 
steve@vm-ocpp:~/steve-steve-3.4.9$ diff ./src/main/resources/config/prod/main.properties ../steve-steve-3.4.8/src/main/resources/config/prod/main.properties
steve@vm-ocpp:~/steve-steve-3.4.9$

Files are equal.

Does this
[ERROR] /home/steve/steve-steve-3.4.9/src/main/java/de/rwth/idsg/steve/repository/impl/ChargePointRepositoryImpl.java:[60,35] cannot find symbol
  symbol:   class ConnectorStatus

mean there is a table ConnectorStatus missing?

**Comment by goekay** [comment]
let's analyse it backwards. it means that a java class ConnectorStatus is missing. this class is generated during the build process by maven plugin of jooq. 

why could maven plugin of jooq not generate the class? either a) the plugin could not access the database, or b) the table was not there.

**Comment by rahulbhat13** [comment]
Increase the memory when your building the mvn package might solve the issue

**Comment by kibeki** [comment]
The memory was not the problem. The problem was that I added two database views into stevedb. 
After I deleted them the compilation worked.
Thanks to you feedback.

**Comment by goekay** [comment]
cool. feel free to close this issue then.
