### ISSUE TITLE
Unable to Stop  Remote Transaction

### ISSUE THREAD

**Issue by subhankar007b** [RWTH-i5-IDSG/steve#796]
Hi there,
I'm able to start Remote Transaction but after that, it's unable to store transaction data in the database. And I'm unable to stop transactions. Please if someone guides me on what I'm doing wrong will be helpful.

Thanks in Advance.

**Comment by goekay** [comment]
> it's unable to store transaction data in the database.

why is this? can you post logs?

obviously, if the transaction cannot be stored in database, you will not be able to stop it since there will not be any transaction to reference.

**Comment by subhankar007b** [comment]
![Screenshot 2022-04-04 235714](https://user-images.githubusercontent.com/102990283/161608835-a0fc03fc-530e-4fd5-a2b6-adf0e30d6ff1.png)
after giving the command remotestarttransaction, charger gets started but after that, in the database no value gets stored. and im unable to stop that transaction

**Comment by goekay** [comment]
assuming that the logs are complete, your charging station appears to not send a StartTransaction message after which steve would have stored the transaction in database.

this was a known problem for a manufacturer/model/firmware. is your charging station, by any chance, one of the mentioned ones here? https://github.com/RWTH-i5-IDSG/steve/issues/740

**Comment by subhankar007b** [comment]
i have TELLUS POWER charger

**Comment by goekay** [comment]
well, i cannot be more helpful than this, please contact the manufacturer. the station does not send the StartTransaction message.

**Comment by subhankar007b** [comment]
okay... thank you for your response.

**Comment by parvesh-shadow** [comment]
@subhankar007b we are looking for support on OCPP had you successfully implemented it. We are looking for some support on it. Ready to pay for it.
