### ISSUE TITLE
Time Different At Connection Status web page

### ISSUE THREAD

**Issue by emry78** [RWTH-i5-IDSG/steve#799]
#### Checklist

- [/ ] I checked other issues already, but found no answer/solution
- [/ ] I checked the documentation and wiki, but found no answer/solution
- [3.4.8 ] I am running the latest version and the issue still occurs
- [/ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.8
Operating system  : Ubuntu 21.04
JDK               : 11.0.13
Database          : 10.5.13
```

#### Expected Behavior
expected time connection same with system
...

#### Actual Behavior
Time setting all set. Please advice if have any setting need

![Screenshot 2022-04-07 143427](https://user-images.githubusercontent.com/49600677/162136419-dfd6c7e1-e61d-49ec-9de2-f6538fd15040.jpg)

time at Connection Status:
![Screenshot 2022-04-07 144451](https://user-images.githubusercontent.com/49600677/162136690-6739e67d-e0c3-4d53-bf16-8eb8049b40cd.jpg)

#### Steps to Reproduce the Problem

  1. go to home page
  2. select connection status
  3. At connection status the time not same as we set all time system.

#### Additional context

no

**Comment by goekay** [comment]
in this table steve shows the date/time of the status message that the charging station sent. there is no intermediate logic or interpretation happening. i would assume that the station does not send proper ISO 8601 date/times. historically we had many issues where the stations had faulty implementations wrt. time zones.

**Comment by goekay** [comment]
since there is no further activity/discussion, i am closing this issue.
