### ISSUE TITLE
{RePOrt} nO nEEd User Pass Login

### ISSUE THREAD

**Issue by AhrimanSefid** [RWTH-i5-IDSG/steve#849]
Version: | 3.4.5
-- | --
Database Version: | 1.0.3
Last Database Update: | 2022-02-24 at 06:53
Log File: | /root/logs/steve.log
GitHub Page: | https://github.com/RWTH-i5-IDSG/steve
System Time: | 2022-06-25T16:11:55.676Z
System Time Zone: | UTC

Sample:

http://112.74.82.53:8181/ocpp-server/manager/users

http://112.74.82.74:8181/ocpp-server/manager/home

**Comment by goekay** [comment]
thanks, but i am not sure what we should do about this (we as in: the maintainers of the open source project). we are not operating these instances. in fact, we are not operating any instance. there is a user login and password for prod environment. the installation readme even walks you through a step where the change of the default password is a must.

the operators of these instances removed the guard of the login mechanism with password. it was an active decision.
