### ISSUE TITLE
Feature req.: Show all chargeboxes and connectors

### ISSUE THREAD

**Issue by TechOverflow** [RWTH-i5-IDSG/steve#87]
In the connector status view, you can only see the latest status for one (latest) connector per chargebox. Would it be possible to show chargeboxes and all their connectors’ status?

Eg.:
CB001 con 0 available
CB001 con 1 occupied
CB001 con 2 available
CB002 con 0 fault
CB002 con 1 fault

Second, more of a question than feature request, I noticed that tasks are purged from the database upon restart. Is there a way to prevent this?

**Comment by goekay** [comment]
> In the connector status view, you can only see the latest status for one (latest) connector per chargebox. Would it be possible to show chargeboxes and all their connectors’ status?

this is actually the case. you can always see latest status of all connectors... with the exception of 0. 0 is a special connector id reserved for the whole charging station. and here comes our special logic: if the station sends a more recent status for 0, we override all the previous status of other connectors and only display 0. the example you gave was the previous implementation, i.e. displaying all status for all connectors without any interpretation. but then we decided, that 0 should have an upper hand and that we should make it really clear that there is something wrong with the whole station (e.g. for fault status).

> Second, more of a question than feature request, I noticed that tasks are purged from the database upon restart. Is there a way to prevent this?

tasks are never written to a database. they are always only in memory. sure, we can write them to a database, but this is a little bit of work. i cannot say when this will be implemented.
