### ISSUE TITLE
Bulk upload of OCPP tags

### ISSUE THREAD

**Issue by rdc-Green** [RWTH-i5-IDSG/steve#870]
I'm trying to upload multiple OCPP tags. Will the ocpp_tg_pk automatically update for each new row added?

**Comment by rdc-Green** [comment]
thank you @mosea3

**Comment by fluppie** [comment]
@mosea3 is this: "I'd recommend importing from CSV over command line" explained somewhere? Or I'm I completely blind for not having found the instructions?

**Comment by goekay** [comment]
> Steve has no bulk import function yet.

not quite true. if you go to ocpp tags page, and click on "Add New", you will be presented with a page that contains two sections: Add OCPP Tag (which is the default) and Add OCPP Tag List above it which an be toggled on. then you can paste into the text area your tags to be bulk-inserted ;)

<img width="930" alt="Screenshot 2024-08-16 at 15 57 16" src="https://github.com/user-attachments/assets/266926fb-e40f-4d8f-92c8-3cbfa811a6fc">

**Comment by fluppie** [comment]
How could I have missed that...
Is it hard to create the same for users?
At the moment I have a file with a name and a tag ID, coolest would be to import them in one go:
User1 00112233445566778899
User2 99887766554433221100
