### ISSUE TITLE
/bin/sh: 1: dockerize: Exec format error

### ISSUE THREAD

**Issue by JeeKee80** [RWTH-i5-IDSG/steve#871]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
SteVe Version     : 3.4.9
Operating system  : arm64,debian(raspberry)
JDK               : latest
Database          : latest
```
Installed as described in docker section from readme (edited the config files as instructed). All installs well, but when trying to run the app it gives me a "/bin/sh: 1: dockerize: Exec format error" error. Not sure what's going on... arm64 issue?

Any help greatly appreciated

**Comment by royalpenguin** [comment]
The `dockerize` binary architecture is hard-coded in the `Dockerfile` file and will not work on ARM like this.
As a workaround you can change the downloaded [binary architecture](https://github.com/jwilder/dockerize/releases/tag/v0.6.1) to the one on your device. E.g.:

```
ARG ARCHITECTURE=armel

# Download and install dockerize.
# Needed so the web container will wait for MariaDB to start.
ENV DOCKERIZE_VERSION v0.6.1
RUN wget --no-verbose https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-$ARCHITECTURE-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-$ARCHITECTURE-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-$ARCHITECTURE-$DOCKERIZE_VERSION.tar.gz

```
