### ISSUE TITLE
Fix formatting of BigDecimals in JSON serialization

### ISSUE THREAD

**Issue by chuck-h** [RWTH-i5-IDSG/steve#93]
By default some fields can get serialized in exponential notation; fixed by this:
https://github.com/chuck-h/steve/commit/20eb524b43f2fbff67137aead2cf2ce49f277593

**Comment by goekay** [comment]
good catch and thanks for the fix. the usage of this feature is deprecated though. i will commit the same semantical change with the suggested usage.
